In [3066]:
import pandas as pd
import numpy as np

In [3067]:
df2020 = pd.read_csv('Salaries Dec 2020.csv')
df2021 = pd.read_csv('Salaries Dec 2021.csv')
df2022 = pd.read_csv('Salaries Dec 2022.csv')
df2023 = pd.read_csv('Salaries Dec 2023.csv')
df2024 = pd.read_csv('Salaries Dec 2024.csv')

## 2020 Dataset

In [3068]:
df2020.columns

Index(['timestamp', 'Ви працюєте зараз в ІТ?', 'Де ви мешкаєте?',
       'Де ви працюєте?', 'male', 'age', 'education',
       'Вкажіть заклад вищої освіти', 'english_level', 'Оберіть вашу посаду',
       'Ваш тайтл', 'Вкажіть вашу спеціалізацію', 'Основна мова програмування',
       'Інші мови програмування', 'Фреймворки, бібліотеки та платформи',
       'Платформи, для яких розробляєте на поточному місці роботи?',
       'Ваш тайтл_1', 'Вкажіть вашу спеціалізацію_2', 'programming_language',
       'Оберіть вашу посаду_3', 'Ваш тайтл_4', 'Ваша посада', 'Ваш тайтл_5',
       'Оберіть вашу посаду_6', 'Ваш тайтл_7', 'Ваша посада_8', 'Ваш тайтл_9',
       'Ваша посада_10', 'Ваш тайтл_11', 'Ваша посада_12', 'Ваш тайтл_13',
       'Ваша посада_14', 'Ваш тайтл_15', 'Ваша посада_16',
       'В якій сфері працюєте?', 'Тип компанії', 'number_of_employees',
       'total_experience', 'Стаж на поточному місці роботи',
       'У скількох компаніях встигли попрацювати за час ІТ-кар'єри?', 'salary',
       'salary_change', 'Чи отримуєте ви грошові бонуси до зарплати?',
       'Вкажіть суму цього бонуса у $$$ після податків'],
      dtype='object')

In [3069]:
df2020 = df2020.rename(columns={'Ви працюєте зараз в ІТ?': 'full_time', 
                                'Де ви мешкаєте?': 'region',
                                'Де ви працюєте?': 'work_site',
                                'Вкажіть заклад вищої освіти': 'university',
                                'Оберіть вашу посаду': 'position',
                                'Ваш тайтл': 'title',
                                'В якій сфері працюєте?': 'industry',
                                'Тип компанії': 'company_type',
                                'Стаж на поточному місці роботи': 'tenure',
                                'Вкажіть суму цього бонуса у $$$ після податків': 'bonus',
                                'Фреймворки, бібліотеки та платформи': 'frameworks',})

df2020['full_time'] = df2020.apply(lambda x: 1 if x['full_time'] == 'Так, працюю full-time' else 0, axis=1)

df2020['programming_language'] = df2020['programming_language'].fillna(df2020['Основна мова програмування'])

df2020['title'] = df2020['title'].fillna(df2020['Ваш тайтл_1']).fillna(df2020['Ваш тайтл_4']).fillna(df2020['Ваш тайтл_5']).fillna(df2020['Ваш тайтл_7']).fillna(df2020['Ваш тайтл_9']).fillna(df2020['Ваш тайтл_11']).fillna(df2020['Ваш тайтл_13']).fillna(df2020['Ваш тайтл_15'])

df2020.drop(columns=['Вкажіть вашу спеціалізацію', 'Вкажіть вашу спеціалізацію_2', 'Інші мови програмування', 'Ваш тайтл_1',
                     'Ваш тайтл_4', 'Ваш тайтл_5', 'Ваш тайтл_7', 'Ваш тайтл_9', 'Ваш тайтл_11', 'Ваш тайтл_13', 'Ваш тайтл_15',
                     'Оберіть вашу посаду_3', 'Ваша посада', 'Оберіть вашу посаду_6', 'Ваша посада_8', 'Ваша посада_10',
                     'Ваша посада_12', 'Ваша посада_14', 'Ваша посада_16', 'Чи отримуєте ви грошові бонуси до зарплати?', 'Основна мова програмування',
                     "У скількох компаніях встигли попрацювати за час ІТ-кар'єри?", 'Платформи, для яких розробляєте на поточному місці роботи?'], inplace=True)

In [ ]:
def convert_tenure(value):
    if "рік" in value or "роки" in value or "років" in value:
        return float(value.split()[0])
    elif "10 і більше" in value:
        return 10
    elif "Менше як 3 місяці" in value:
        return 0.25
    elif "Пів року" in value:
        return 0.5
    elif "3 місяці" in value:
        return 0.25
    return None  # For unexpected values

df2020['tenure'] = df2020['tenure'].apply(convert_tenure)

## 2021 Dataset

In [3071]:
df2021.columns

Index(['timestamp', 'Ви працюєте зараз в ІТ?', 'Де ви мешкаєте?',
       'Де ви працюєте?', 'male', 'age', 'education',
       'Чи є у вас науковий ступінь? ', 'english_level', 'Оберіть вашу посаду',
       'Ваш тайтл', 'Ваш тайтл.1', 'Вкажіть вашу спеціалізацію',
       'Оберіть вашу посаду.1', 'Ваш тайтл.2', 'Ваша посада', 'Ваш тайтл.3',
       'Оберіть вашу посаду.2', 'Ваш тайтл.4', 'Ваша посада.1', 'Ваш тайтл.5',
       'Ваша посада.2', 'Ваш тайтл.6', 'Ваша посада.3', 'Ваш тайтл.7',
       'Ваша посада.4', 'Ваш тайтл.8', 'Ваш тайтл.9', 'Ваша посада.5',
       'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',
       'programming_language', 'Інші мови програмування',
       'Платформи, для яких розробляєте на поточному місці роботи?',
       'Вкажіть вашу основну спеціалізацію', 'В якій сфері працюєте?',
       'Тип компанії', 'number_of_employees', 'Загальний стаж роботи в ІТ',
       'total_experience',
       'У скількох компаніях встигли попрацювати за час ІТ-кар'єри?', 'salary',
       'salary_change', 'Ставка у $$$ за годину, яку ви виставляєте клієнтам',
       'Чи отримуєте ви грошові бонуси до зарплати?',
       'Вкажіть суму цього бонуса у $$$ після податків'],
      dtype='object')

In [3072]:
df2021 = df2021.rename(columns={'Ви працюєте зараз в ІТ?': 'full_time', 
                                'Де ви мешкаєте?': 'region',
                                'Де ви працюєте?': 'work_site',
                                'Чи є у вас науковий ступінь? ': 'phd',
                                'Оберіть вашу посаду': 'position',
                                'Ваш тайтл': 'title',
                                'В якій сфері працюєте?': 'industry',
                                'Тип компанії': 'company_type',
                                'Вкажіть суму цього бонуса у $$$ після податків': 'bonus',})

df2021['full_time'] = df2021.apply(
    lambda x: 1 if x['full_time'] == 'Так, працюю full-time' else 0, axis=1)

df2021['title'] = df2021['title'].fillna(df2021['Ваш тайтл.1']).fillna(df2021['Ваш тайтл.2']).fillna(df2021['Ваш тайтл.3']).fillna(df2021['Ваш тайтл.4']).fillna(df2021['Ваш тайтл.5']).fillna(df2021['Ваш тайтл.6']).fillna(df2021['Ваш тайтл.7']).fillna(df2021['Ваш тайтл.8']).fillna(df2021['Ваш тайтл.9'])

df2021.drop(columns=['Вкажіть вашу спеціалізацію', 'Оберіть вашу посаду.1', 'Оберіть вашу посаду.2', 'Інші мови програмування', 'Платформи, для яких розробляєте на поточному місці роботи?',
    'Чи отримуєте ви грошові бонуси до зарплати?', 'Ставка у $$$ за годину, яку ви виставляєте клієнтам', 'Вкажіть вашу основну спеціалізацію', "У скількох компаніях встигли попрацювати за час ІТ-кар'єри?",
    'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?', 'Ваша посада','Ваша посада.1', 'Ваша посада.2', 'Ваша посада.3', 'Ваша посада.4', 'Ваша посада.5',
    'Ваш тайтл.1','Ваш тайтл.2', 'Ваш тайтл.3', 'Ваш тайтл.4', 'Ваш тайтл.5', 'Ваш тайтл.6', 'Ваш тайтл.7', 'Ваш тайтл.8', 'Ваш тайтл.9', 'Загальний стаж роботи в ІТ'], inplace=True)

## 2022 Dataset

In [3073]:
df2022.columns

Index(['timestamp', 'Ви працюєте зараз в ІТ?', 'Де ви зараз живете? ',
       'В якій області ви зараз живете?', 'salary', 'male', 'age', 'education',
       'Чи є у вас науковий ступінь? ', 'english_level', 'Оберіть вашу посаду',
       'Ваш тайтл', 'Ваша спеціалізація', 'Вкажіть вашу спеціалізацію',
       'Оберіть вашу спеціалізацію', 'Ваша посада', 'Оберіть вашу посаду2',
       'Ваша посада3', 'Ваша посада4', 'Ваша посада5', 'Ваша посада6',
       'Ваша посада7',
       'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',
       'programming_language', 'Вкажіть вашу основну спеціалізацію',
       'В якій сфері працюєте?', 'Тип компанії', 'total_experience'],
      dtype='object')

In [3074]:
df2022 = df2022.rename(columns={'Ви працюєте зараз в ІТ?': 'full_time', 
                                'В якій області ви зараз живете?': 'region',
                                'Де ви працюєте?': 'work_site',
                                'Чи є у вас науковий ступінь? ': 'phd',
                                'Оберіть вашу посаду': 'position',
                                'Ваш тайтл': 'title',
                                'В якій сфері працюєте?': 'industry',
                                'Тип компанії': 'company_type',
                                'Вкажіть суму цього бонуса у $$$ після податків': 'bonus',})

df2022['full_time'] = df2022.apply(
    lambda x: 1 if x['full_time'] == 'Так, працюю full-time' else 0, axis=1)

df2022['region'] = df2022['region'].str.extract(r'^(.*?)\s+чи\s+область')
df2022['region'] = df2022.apply(
    lambda x: "Не Україна" if pd.isna(x['region']) else x["region"], axis=1)


df2022.drop(columns=['Де ви зараз живете? ', 'Оберіть вашу посаду2', 'Оберіть вашу спеціалізацію', 'Вкажіть вашу основну спеціалізацію',
       'Ваша посада3', 'Ваша посада4', 'Ваша посада5', 'Ваша посада6', 'Ваша спеціалізація', 'Вкажіть вашу спеціалізацію', 'Ваша посада',
       'Ваша посада7', 'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',], inplace=True)

## 2023 Dataset

In [3075]:
df2023.columns

Index(['timestamp', 'Ваша основна зайнятість в ІТ зараз...',
       'Зарплата / дохід в IT у $$$ за місяць, лише ставка ЧИСТИМИ - після сплати податків',
       'Оберіть ваш тайтл або роль у компанії', 'Categories', 'Position',
       'Розробники -  основна спеціалізація', 'programming_language',
       'Основний напрям роботи компанії, в якій працюєте', 'total_experience',
       'english_level', 'Де ви зараз живете?',
       'В якій області ви зараз живете?', 'male'],
      dtype='object')

In [3076]:
df2023 = df2023.rename(columns={'Ваша основна зайнятість в ІТ зараз...': 'full_time', 
                                'Зарплата / дохід в IT у $$$ за місяць, лише ставка ЧИСТИМИ - після сплати податків': 'salary',
                                'Основний напрям роботи компанії, в якій працюєте': 'company_type',
                                'Оберіть ваш тайтл або роль у компанії': 'title',
                                'В якій області ви зараз живете?': 'region',})

df2023['full_time'] = df2023.apply(
    lambda x: 1 if x['full_time'] == 'Працюю full-time' else 0, axis=1)

valid_titles = ["Middle", "Senior", "Junior", "Head", "Intern/Trainee", 
                "Architect", "Tech Lead", "Team Lead", "Manager"]
df2023['title'] = df2023['title'].apply(lambda x: x if x in valid_titles else None)


df2023['region'] = df2023['region'].str.extract(r'^(.*?)\s+чи\s+область')
df2023['region'] = df2023.apply(
    lambda x: "Не Україна" if pd.isna(x['region']) else x["region"], axis=1)

df2023['male'] = df2023.apply(lambda x: 1 if x['male'] == 1.0 else 0, axis=1)
df2023['categories'] = df2023["Categories"]
df2023['position'] = df2023['Position']

df2023.drop(columns=['Де ви зараз живете?', 'Categories', 'Position', 'Розробники -  основна спеціалізація'], inplace=True)

## 2024 Dataset

In [3077]:
df2024.columns

Index(['timestamp', 'Ваша основна зайнятість в ІТ зараз...',
       'Зарплата / дохід в IT у $$$ за місяць, лише ставка ЧИСТИМИ - після сплати податків',
       'Оберіть ваш тайтл або роль у компанії', 'Categories', 'Position',
       'Розробники -  основна спеціалізація', 'programming_language',
       'Основний напрям роботи компанії, в якій працюєте',
       'Загальний стаж роботи за нинішньою ІТ-спеціальністю', 'english_level',
       'Де ви зараз живете?', 'В якій області ви зараз живете?', 'male'],
      dtype='object')

In [3078]:
df2024 = df2024.rename(columns={'Ваша основна зайнятість в ІТ зараз...': 'full_time', 
                                'Зарплата / дохід в IT у $$$ за місяць, лише ставка ЧИСТИМИ - після сплати податків': 'salary',
                                'Основний напрям роботи компанії, в якій працюєте': 'company_type',
                                'Оберіть ваш тайтл або роль у компанії': 'title',
                                'В якій області ви зараз живете?': 'region',})

df2024['full_time'] = df2024.apply(
    lambda x: 1 if x['full_time'] == 'Працюю full-time' else 0, axis=1)

valid_titles = ["Middle", "Senior", "Junior", "Head", "Intern/Trainee", 
                "Architect", "Tech Lead", "Team Lead", "Manager"]
df2024['title'] = df2024['title'].apply(lambda x: x if x in valid_titles else None)


df2024['region'] = df2024['region'].str.extract(r'^(.*?)\s+чи\s+область')
df2024['region'] = df2024.apply(
    lambda x: "Не Україна" if pd.isna(x['region']) else x["region"], axis=1)

df2024['male'] = df2024.apply(lambda x: 1 if x['male'] == 1.0 else 0, axis=1)
df2024['categories'] = df2024["Categories"]
df2024['position'] = df2024['Position']

df2024.drop(columns=['Де ви зараз живете?', 'Categories', 'Position', 'Розробники -  основна спеціалізація', 'Загальний стаж роботи за нинішньою ІТ-спеціальністю'], inplace=True)

## Check for missing/incorrect value

### Programming language

In [3079]:
print('programming_language',df2020['programming_language'].unique())
print("\n")
print('programming_language',df2021['programming_language'].unique())
print("\n")
print('programming_language',df2022['programming_language'].unique())
print("\n")
print('programming_language',df2023['programming_language'].unique())
print("\n")
print('programming_language',df2024['programming_language'].unique())
print("\n")

programming_language [nan 'Java' 'Kotlin' '1С' 'Ruby' 'JavaScript' 'Python' 'PHP' 'C++' 'C#'
 'C#/.NET' 'Swift' 'Не використовую' 'TypeScript' 'Scala' 'Rust' 'Go'
 'Іншу' 'SQL' 'Clojure' 'Elixir' 'Erlang' 'C' 'Інше' 'Perl' 'Objective-C'
 'Dart' 'Haskell' 'ABAP' 'Delphi' 'Assembler' 'APL' 'R' 'Groovy'
 'Flex/Flash/AIR']


programming_language [nan 'Python' 'PHP' 'Інша мова' 'Не можу обрати одну основну мову' 'SQL'
 'Java' 'JavaScript' 'Мови розробки БД (PL/SQL, Transact-SQL)' 'Ruby'
 'C# / .NET' 'R' 'Salesforce Apex' 'Scala' 'TypeScript' 'Kotlin' 'Go' '1С'
 'Groovy' 'C' 'C++' 'Pascal/Delphi' 'Swift' 'ABAP' 'Perl' 'Dart' 'Clojure'
 'Assembler' 'Erlang' 'Haskell' 'Elixir' 'Rust' 'Objective-C' 'APL']


programming_language [nan 'Ruby' 'C# / .NET' 'PHP' 'Python' 'TypeScript' 'JavaScript' 'Kotlin'
 'Rust' 'Perl' 'Java' 'Groovy' 'Інша мова' 'C' 'Swift' 'Scala' 'C++' '1С'
 'SQL' 'Salesforce Apex' 'Dart' 'Go' 'Не можу обрати одну основну мову'
 'Elixir' 'Мови розробки БД (PL/SQL, Transact-SQL)' 'R' 'Objective-C'
 'APL' 'Pascal/Delphi' 'Erlang' 'ABAP' 'Clojure' 'Haskell'
 'Flex / Flash / AIR']


programming_language ['TypeScript' 'C# / .NET' 'Python' 'PHP' 'Java' nan 'JavaScript' 'Kotlin'
 'C' 'Не можу обрати одну основну мову' 'C++' 'SQL'
 'Мови розробки БД (PL/SQL, Transact-SQL)' 'Salesforce Apex' 'Go' 'Scala'
 '1С' 'Dart' 'Other' 'Swift' 'VBA' 'Groovy' 'Ruby' 'ABAP' 'Clojure'
 'autoit' 'Pascal/Delphi' 'Bash' 'DAX' 'R' 'bash' 'Codeless' 'Perl'
 'Solidity' 'KQL' 'PowerShell' 'Rust' 'Erlang' 'Elixir' 'X++ / D365' 'APL'
 'SAS' 'bash scripting' 'powershell' 'Objective-C' 'Liquid' 'BASH' 'Lua'
 'Powershell' 'Power Platfrom' 'SenseTalk' 'AL' 'Haskell' 'SAS, SQL'
 'Ніякої' 'CSS' 'SCSS' 'Flex / Flash / AIR' 'DAX, M'
 'FlexiLayout Language' 'Verilog' 'ampscript' 'Blueprints' 'Bash/Shell'
 'Dax' 'BrightScript' 'Cmd, bash' 'C/AL' 'MATLAB' 'Bash,YAML, HCL' 'Gosu'
 'Bash, terraform' 'Outsystems' 'F#' 'bash:)' 'LAD' 'M,DAX,SQL' 'Vbscript'
 'non-tech' 'SystemVerilog' 'Зараз більше Архітектурної роботи']


programming_language ['TypeScript' 'C# / .NET' 'Python' 'PHP' 'Java' nan 'JavaScript' 'Kotlin'
 'C' 'Не можу обрати одну основну мову' 'C++' 'SQL'
 'Мови розробки БД (PL/SQL, Transact-SQL)' 'Salesforce Apex' 'Go' 'Scala'
 '1С' 'Dart' 'Other' 'Swift' 'VBA' 'Groovy' 'Ruby' 'ABAP' 'Clojure'
 'autoit' 'Pascal/Delphi' 'Bash' 'DAX' 'R' 'bash' 'Codeless' 'Perl'
 'Solidity' 'KQL' 'PowerShell' 'Rust' 'Erlang' 'Elixir' 'X++ / D365' 'APL'
 'SAS' 'bash scripting' 'powershell' 'Objective-C' 'Liquid' 'BASH' 'Lua'
 'Powershell' 'Power Platfrom' 'SenseTalk' 'AL' 'Haskell' 'SAS, SQL'
 'Ніякої' 'CSS' 'SCSS' 'Flex / Flash / AIR' 'DAX, M'
 'FlexiLayout Language' 'Verilog' 'ampscript' 'Blueprints' 'Bash/Shell'
 'Dax' 'BrightScript' 'Cmd, bash' 'C/AL' 'MATLAB' 'Bash,YAML, HCL' 'Gosu'
 'Bash, terraform' 'Outsystems' 'F#' 'bash:)' 'LAD' 'M,DAX,SQL' 'Vbscript'
 'non-tech' 'SystemVerilog' 'Зараз більше Архітектурної роботи']

In [3080]:
#check
df2020['programming_language'] = df2020['programming_language'].apply(lambda x: None if x == 'Не використовую' else x)
df2021['programming_language'] = df2021['programming_language'].apply(lambda x: None if x == 'Не можу обрати одну основну мову' else x)
df2022['programming_language'] = df2022['programming_language'].apply(lambda x: None if x == 'Не можу обрати одну основну мову' else x)
df2023['programming_language'] = df2023['programming_language'].apply(lambda x: None if x == 'Не можу обрати одну основну мову' or x == 'Зараз більше Архітектурної роботи' or x == "Ніякої" else x)
df2024['programming_language'] = df2024['programming_language'].apply(lambda x: None if x == 'Не можу обрати одну основну мову' or x == 'Зараз більше Архітектурної роботи' or x == 'Ніякої'  else x)

#dealing
df2020['programming_language'] = df2020['programming_language'].replace({'Іншу': 'Інше'})
df2020['programming_language'] = df2020['programming_language'].replace({None: np.nan})

df2021['programming_language'] = df2021['programming_language'].replace({'Інша мова': 'Інше'})
df2021['programming_language'] = df2021['programming_language'].replace({None: np.nan})

df2022['programming_language'] = df2022['programming_language'].replace({'Інша мова': 'Інше'})
df2022['programming_language'] = df2022['programming_language'].replace({None: np.nan})

df2023['programming_language'] = df2023['programming_language'].replace({'Other': 'Інше'})
df2023['programming_language'] = df2023['programming_language'].replace({None: np.nan})

df2024['programming_language'] = df2024['programming_language'].replace({'Other': 'Інше'})
df2024['programming_language'] = df2024['programming_language'].replace({None: np.nan})

print('programming_language',df2020['programming_language'].unique())
print("\n")

programming_language [nan 'Java' 'Kotlin' '1С' 'Ruby' 'JavaScript' 'Python' 'PHP' 'C++' 'C#'
 'C#/.NET' 'Swift' 'TypeScript' 'Scala' 'Rust' 'Go' 'Інше' 'SQL' 'Clojure'
 'Elixir' 'Erlang' 'C' 'Perl' 'Objective-C' 'Dart' 'Haskell' 'ABAP'
 'Delphi' 'Assembler' 'APL' 'R' 'Groovy' 'Flex/Flash/AIR']

### Industry

In [3081]:
for val in df2020['industry'].unique():
    print(val)
# print("\n")
# print('industry',df2021['industry'].unique())
# print("\n")
# print('industry',df2022['industry'].unique())
# print("\n")

Telecom
Fintech, Medtech
Інша
E-commerce, ERP, Інша
E-commerce
Fintech, Telecom
Medtech, Mobile
Hardware, Telecom
Fintech, Legal, Media
Fintech
Security
Data Science, Geospatial, Hardware
GameDev
Fintech, Gambling, GameDev
Fintech, Travel
GameDev, Mobile
Internet of Things, Legal
ERP
Media
Mobile
Fintech, Internet of Things, Mobile
Data Science, Geospatial, Telecom
Gambling
Automotive, E-commerce, Edtech
E-commerce, High Load Systems, Інша
Adtech, E-commerce
E-commerce, Gambling, GameDev
Adtech
Fintech, Gambling
Cloud Computing, E-commerce
Machine Learning
High Load Systems, Інша
Edtech
Cloud Computing
Adtech, Big Data, High Load Systems
E-commerce, ERP
Medtech
Logistics, Інша
Data Science, E-commerce, Інша
E-commerce, Insurance
Fintech, GameDev
Big Data, Blockchain, Cloud Computing
Edtech, Інша
Automotive, Geospatial, Logistics
Insurance
Cloud Computing, Gambling, Logistics
Blockchain, Інша
Hardware
Cloud Computing, Logistics
E-commerce, Інша
Big Data
Fintech, High Load Systems, Internet of Things
Automotive, Manufacturing, Telecom
Edtech, Mobile, Інша
GameDev, High Load Systems, Travel
E-commerce, Media
E-commerce, Security
ERP, Medtech
Data Science, Fintech, Machine Learning
Fintech, High Load Systems
Insurance, Medtech
Internet of Things
Data Science
E-commerce, Gambling, Media
Big Data, Cloud Computing
Automotive, E-commerce, Fintech
Adtech, Big Data
Travel
Fintech, High Load Systems, Mobile
E-commerce, ERP, Internet of Things
Automotive, Gambling, Internet of Things
Big Data, Cloud Computing, Travel
Media, Інша
Big Data, Security
Big Data, Cloud Computing, Media
Big Data, Fintech
Embedded, Internet of Things, Telecom
Blockchain
Data Science, Machine Learning
Big Data, High Load Systems
E-commerce, Fintech
Big Data, Data Science, Gambling
Automotive
Data Science, Machine Learning, Medtech
E-commerce, Logistics, Travel
High Load Systems
Logistics
Cloud Computing, ERP, Fintech
Fintech, Logistics
Internet of Things, Robotics
Automotive, Machine Learning
E-commerce, Medtech
Fintech, Manufacturing, Security
Hardware, Machine Learning, Medtech
Cloud Computing, Embedded, Telecom
E-commerce, Media, Medtech
Big Data, E-commerce, Media
Big Data, Fintech, Mobile
ERP, Medtech, Інша
Media, Mobile
Cloud Computing, Data Science, Machine Learning
Embedded
Big Data, Machine Learning, Security
Blockchain, Fintech
Cloud Computing, Data Science
Embedded, Hardware, Telecom
Logistics, Mobile, Інша
Insurance, Інша
Big Data, E-commerce, High Load Systems
E-commerce, GameDev, Mobile
Big Data, Cloud Computing, Security
Cloud Computing, High Load Systems, Logistics
Big Data, Data Science
E-commerce, Fintech, Manufacturing
E-commerce, Fintech, Gambling
Blockchain, Fintech, Mobile
Blockchain, Gambling
Internet of Things, Machine Learning, Medtech
Blockchain, Fintech, High Load Systems
Embedded, Hardware, Machine Learning
Cloud Computing, Insurance
Cloud Computing, Fintech
Gambling, GameDev
E-commerce, Fintech, Mobile
Internet of Things, Medtech, Travel
Cloud Computing, E-commerce, Internet of Things
AR/VR, GameDev
Big Data, Cloud Computing, High Load Systems
Machine Learning, Інша
Medtech, Travel
Logistics, Travel, Uberfication
Machine Learning, Medtech
E-commerce, High Load Systems, Travel
ERP, Інша
Hardware, Insurance, Logistics
Adtech, Mobile
Adtech, Cloud Computing, High Load Systems
Big Data, Data Science, Internet of Things
Blockchain, Mobile
E-commerce, Travel
Manufacturing, Medtech
E-commerce, Logistics, Інша
High Load Systems, Insurance, Mobile
Automotive, High Load Systems
Embedded, Hardware, Internet of Things
Embedded, Telecom, Інша
Automotive, E-commerce
E-commerce, Logistics
Gambling, Media
Automotive, Internet of Things, Mobile
Fintech, Medtech, Travel
Manufacturing
Big Data, Mobile
Gambling, Mobile, Інша
Cloud Computing, High Load Systems, Internet of Things
Security, Telecom
Cloud Computing, E-commerce, Insurance
Adtech, Gambling
Data Science, Fintech, Mobile
High Load Systems, Insurance, Internet of Things
AR/VR, E-commerce, Edtech
ERP, Legal
Embedded, Hardware
Cloud Computing, High Load Systems, Insurance
Medtech, Mobile, Інша
Automotive, Logistics, Machine Learning
Cloud Computing, High Load Systems
High Load Systems, Internet of Things, Media
Adtech, Travel
Logistics, Uberfication
Logistics, Mobile, Travel
Big Data, Cloud Computing, Logistics
Big Data, Data Science, Machine Learning
ERP, Mobile
Adtech, Media
Uberfication
Cloud Computing, Security
Media, Mobile, Security
Automotive, Embedded
Machine Learning, Telecom
Data Science, Embedded, High Load Systems
Embedded, Інша
Insurance, Legal
E-commerce, Mobile
Internet of Things, Інша
Medtech, Robotics
Automotive, Embedded, Robotics
E-commerce, Fintech, Travel
Media, Security, Telecom
Robotics
ERP, High Load Systems, Інша
Fintech, Gambling, Legal
Automotive, ERP, Legal
E-commerce, Insurance, Logistics
Hardware, Medtech, Mobile
Fintech, High Load Systems, Telecom
E-commerce, ERP, Logistics
Gambling, Media, Інша
E-commerce, High Load Systems, Media
Embedded, Telecom
E-commerce, Gambling
Cloud Computing, ERP, Medtech
Automotive, Machine Learning, Medtech
Cloud Computing, ERP
Automotive, Fintech
E-commerce, Fintech, Інша
Adtech, GameDev
Data Science, E-commerce
Legal
AR/VR, Cloud Computing, Telecom
Data Science, Machine Learning, Media
Embedded, Hardware, Mobile
Cloud Computing, E-commerce, ERP
Fintech, Інша
E-commerce, Machine Learning, Mobile
Automotive, Fintech, Media
ERP, Fintech, Legal
Embedded, Machine Learning, Security
Agriculture
Geospatial, Інша
High Load Systems, Media
AR/VR
Fintech, Manufacturing
Embedded, Internet of Things
AR/VR, Big Data, Mobile
Fintech, Legal
Fintech, Security
Automotive, Cloud Computing, ERP
Automotive, E-commerce, Travel
Automotive, E-commerce, Media
Internet of Things, Machine Learning, Інша
E-commerce, ERP, Fintech
Big Data, Cloud Computing, Data Science
E-commerce, GameDev, High Load Systems
Logistics, Travel
E-commerce, Telecom
Big Data, Blockchain
Geospatial, Mobile
Legal, Medtech, Інша
Big Data, Geospatial
Gambling, Інша
Insurance, Logistics, Medtech
E-commerce, High Load Systems
GameDev, Mobile, Travel
Cloud Computing, Media, Mobile
Hardware, Mobile
Fintech, Media, Mobile
Hardware, Internet of Things, Telecom
Fintech, Mobile, Travel
Adtech, E-commerce, Fintech
Automotive, Embedded, Hardware
Mobile, Security, Інша
Big Data, Internet of Things, Telecom
Automotive, High Load Systems, Internet of Things
E-commerce, Logistics, Security
E-commerce, Legal, Mobile
Medtech, Інша
Adtech, Gambling, Media
ERP, Mobile, Інша
Cloud Computing, Internet of Things
Hardware, Logistics, Media
Insurance, Telecom
Automotive, Security
Legal, Logistics, Mobile
Big Data, Cloud Computing, Embedded
E-commerce, Manufacturing, Mobile
Automotive, Manufacturing
Blockchain, Cloud Computing, Edtech
Manufacturing, Media, Інша
Big Data, GameDev, High Load Systems
Media, Medtech
Media, Mobile, Telecom
High Load Systems, Manufacturing
Data Science, Geospatial, Machine Learning
Adtech, Cloud Computing, Інша
E-commerce, Logistics, Mobile
Adtech, Big Data, Geospatial
Adtech, High Load Systems
Fintech, Internet of Things, Logistics
Big Data, Cloud Computing, Machine Learning
E-commerce, Embedded, Telecom
Embedded, Medtech
Blockchain, GameDev
E-commerce, Mobile, Інша
Edtech, Media
Big Data, E-commerce, Fintech
Automotive, Big Data
Agriculture, Big Data, Cloud Computing
Machine Learning, Mobile
Fintech, Insurance
Fintech, Security, Telecom
E-commerce, Machine Learning, Telecom
Embedded, High Load Systems, Internet of Things
Data Science, Machine Learning, Інша
Automotive, Big Data, Manufacturing
Automotive, Embedded, Internet of Things
Mobile, Telecom
Cloud Computing, Edtech
Cloud Computing, Hardware, Mobile
Adtech, Big Data, Medtech
Logistics, Mobile
Embedded, Media, Telecom
Automotive, Logistics
E-commerce, Telecom, Інша
Cloud Computing, Інша
Fintech, Logistics, Telecom
E-commerce, Medtech, Mobile
Agriculture, Fintech
Gambling, Travel, Інша
Cloud Computing, Manufacturing, Travel
Adtech, Fintech, High Load Systems
Cloud Computing, Medtech
E-commerce, Media, Mobile
Big Data, Machine Learning
Cloud Computing, Telecom
E-commerce, Media, Інша
Big Data, Fintech, High Load Systems
Adtech, Big Data, Media
Internet of Things, Media, Telecom
Fintech, Insurance, Logistics
Geospatial
Big Data, Telecom
Fintech, Mobile, Security
High Load Systems, Internet of Things
Hardware, Media
Hardware, Media, Інша
Big Data, Media, Інша
High Load Systems, Security, Telecom
Media, Security
Agriculture, Machine Learning, Robotics
E-commerce, Media, Security
Data Science, E-commerce, ERP
Geospatial, High Load Systems, Mobile
Big Data, Cloud Computing, Інша
Fintech, Insurance, Media
Cloud Computing, E-commerce, Fintech
Embedded, Media
Fintech, Media
High Load Systems, Security
Automotive, Big Data, Geospatial
Agriculture, Big Data, Security
AR/VR, Cloud Computing, Robotics
Blockchain, E-commerce, High Load Systems
Gambling, High Load Systems
E-commerce, Gambling, Medtech
Fintech, High Load Systems, Security
Internet of Things, Logistics
Adtech, Data Science, Machine Learning
Fintech, High Load Systems, Insurance
Manufacturing, Інша
AR/VR, Hardware, Machine Learning
Internet of Things, Medtech, Mobile
Embedded, High Load Systems, Telecom
Automotive, Data Science, Manufacturing
Cloud Computing, Fintech, Machine Learning
Big Data, Geospatial, Machine Learning
Hardware, Security
Big Data, E-commerce, Internet of Things
Automotive, Fintech, Telecom
Automotive, Fintech, Geospatial
Gambling, GameDev, Mobile
Fintech, Insurance, Medtech
Fintech, Manufacturing, Інша
Big Data, Fintech, Media
Cloud Computing, ERP, High Load Systems
High Load Systems, Mobile, Telecom
Big Data, Cloud Computing, E-commerce
Cloud Computing, Internet of Things, Security
Big Data, E-commerce, Інша
Legal, Machine Learning
GameDev, Mobile, Інша
Automotive, Insurance
Mobile, Інша
Legal, Manufacturing
Big Data, E-commerce, ERP
Agriculture, Cloud Computing, E-commerce
E-commerce, Fintech, Internet of Things
Cloud Computing, Hardware, Security
Edtech, Medtech
Big Data, E-commerce
Insurance, Internet of Things
Big Data, Data Science, Insurance
Internet of Things, Mobile, Security
Big Data, Machine Learning, Інша
ERP, Fintech, Machine Learning
E-commerce, Internet of Things, Mobile
Internet of Things, Mobile
Mobile, Security
High Load Systems, Legal
Machine Learning, Security
Geospatial, Media, Security
Hardware, Інша
Adtech, Fintech, Legal
E-commerce, Fintech, Legal
Automotive, Big Data, Telecom
Automotive, Travel
Medtech, Security
High Load Systems, Telecom
Adtech, Fintech, Gambling
Agriculture, Geospatial, Internet of Things
Automotive, Internet of Things, Logistics
Insurance, Security, Інша
Cloud Computing, High Load Systems, Media
Fintech, Internet of Things, Medtech
Agriculture, ERP, Security
Cloud Computing, E-commerce, Medtech
E-commerce, Edtech
Mobile, Travel
Big Data, ERP, Fintech
Travel, Інша
Cloud Computing, Embedded
Adtech, Agriculture, Mobile
E-commerce, Mobile, Travel
Hardware, Internet of Things, Security
Big Data, Data Science, Mobile
Cloud Computing, Internet of Things, Manufacturing
Embedded, Hardware, Media
Embedded, Hardware, Robotics
Data Science, GameDev
Automotive, Telecom
AR/VR, E-commerce
Cloud Computing, E-commerce, Hardware
Internet of Things, Security, Інша
Fintech, Internet of Things, Machine Learning
E-commerce, Legal, Інша
Cloud Computing, Robotics
Blockchain, Mobile, Security
Automotive, Cloud Computing
Agriculture, Automotive, Logistics
Internet of Things, Medtech
E-commerce, Legal
Blockchain, E-commerce, GameDev
Gambling, Mobile
Insurance, Medtech, Інша
Data Science, Insurance
High Load Systems, Media, Medtech
E-commerce, Mobile, Telecom
E-commerce, ERP, Robotics
Fintech, Insurance, Legal
Blockchain, Data Science, E-commerce
Agriculture, Data Science, Geospatial
Cloud Computing, Fintech, Інша
Fintech, High Load Systems, Legal
Legal, Media
Automotive, Edtech
ERP, Fintech, Medtech
GameDev, Internet of Things, Інша
E-commerce, Hardware, Mobile
GameDev, Інша
Cloud Computing, Media
Cloud Computing, E-commerce, High Load Systems
ERP, High Load Systems, Security
Big Data, Data Science, Media
Blockchain, E-commerce, Mobile
E-commerce, Machine Learning
E-commerce, ERP, Manufacturing
Fintech, Security, Travel
High Load Systems, Media, Telecom
Internet of Things, Manufacturing
AR/VR, GameDev, Mobile
E-commerce, Internet of Things
Media, Telecom
Adtech, GameDev, Mobile
Adtech, Fintech, Insurance
Big Data, Gambling, High Load Systems
Big Data, E-commerce, Mobile
Big Data, Gambling, Machine Learning
Logistics, Security, Інша
Media, Mobile, Інша
AR/VR, Machine Learning
Agriculture, Manufacturing
Medtech, Telecom
E-commerce, Manufacturing, Medtech
Media, Security, Інша
Automotive, Інша
Fintech, Mobile
AR/VR, Big Data, Machine Learning
AR/VR, E-commerce, Mobile
Big Data, Інша
Machine Learning, Media
Edtech, Media, Інша
ERP, Telecom
E-commerce, High Load Systems, Medtech
Adtech, Big Data, ERP
Data Science, Medtech, Robotics
E-commerce, Insurance, Medtech
Edtech, Medtech, Mobile
Blockchain, E-commerce, Fintech
E-commerce, ERP, Legal
AR/VR, Automotive, Інша
Big Data, Cloud Computing, Internet of Things
Automotive, Media, Telecom
ERP, Manufacturing
Internet of Things, Security
Data Science, Fintech, Logistics
Big Data, Internet of Things
Gambling, Telecom
Data Science, Media
Fintech, Machine Learning
High Load Systems, Internet of Things, Security
Automotive, Embedded, Telecom
Cloud Computing, High Load Systems, Security
Cloud Computing, ERP, Machine Learning
Blockchain, Fintech, Media
Edtech, GameDev
Big Data, High Load Systems, Internet of Things
Big Data, Blockchain, Fintech
E-commerce, Hardware
Adtech, Manufacturing
Blockchain, Insurance, Mobile
Cloud Computing, Data Science, High Load Systems
Big Data, Media
Data Science, Manufacturing, Інша
Blockchain, Media, Mobile
Data Science, ERP, Logistics
Embedded, Mobile, Travel
Automotive, Data Science, High Load Systems
Big Data, ERP, Insurance
Agriculture, Cloud Computing, Fintech
Big Data, Legal, Інша
Geospatial, High Load Systems, Logistics
Legal, Telecom
ERP, Fintech
Data Science, Machine Learning, Robotics
Fintech, Logistics, Mobile
E-commerce, High Load Systems, Security
Logistics, Media
Travel, Uberfication
GameDev, High Load Systems
Data Science, Fintech
Cloud Computing, E-commerce, Edtech
Big Data, Blockchain, Gambling
Blockchain, Travel
Big Data, Data Science, Інша
Fintech, Medtech, Uberfication
Mobile, Uberfication, Інша
Manufacturing, Mobile
Big Data, Travel
Cloud Computing, Internet of Things, Mobile
Embedded, Internet of Things, Robotics
Agriculture, Cloud Computing, Geospatial
Cloud Computing, Manufacturing, Media
Cloud Computing, Fintech, High Load Systems
Data Science, Embedded
Adtech, Fintech
Big Data, Cloud Computing, ERP
Agriculture, Fintech, Insurance
Adtech, Media, Інша
AR/VR, Mobile, Telecom
Edtech, Travel
Edtech, Fintech, Mobile
Big Data, Insurance
E-commerce, Fintech, Medtech
Internet of Things, Manufacturing, Mobile
Media, Medtech, Інша
Legal, Logistics
Blockchain, Cloud Computing, Robotics
Internet of Things, Machine Learning, Manufacturing
Cloud Computing, Data Science, Internet of Things
Big Data, High Load Systems, Manufacturing
Big Data, E-commerce, Manufacturing
Hardware, Security, Telecom
Adtech, Insurance
Automotive, Geospatial, Mobile
Embedded, Hardware, Інша
AR/VR, Insurance, Medtech
AR/VR, Automotive, Mobile
E-commerce, Mobile, Security
E-commerce, Manufacturing, Robotics
E-commerce, Fintech, Machine Learning
Big Data, Data Science, Fintech
Automotive, Embedded, Mobile
Cloud Computing, Legal, Media
Cloud Computing, Insurance, Інша
AR/VR, Cloud Computing, Data Science
Legal, Інша
Agriculture, Geospatial, Machine Learning
Big Data, Data Science, ERP
E-commerce, High Load Systems, Mobile
E-commerce, Insurance, Telecom
Embedded, Internet of Things, Інша
Hardware, Manufacturing
Cloud Computing, High Load Systems, Mobile
E-commerce, Insurance, Інша
Cloud Computing, Hardware, Telecom
Automotive, Security, Travel
Data Science, Machine Learning, Security
Big Data, High Load Systems, Інша
Data Science, Hardware, Machine Learning
ERP, Fintech, High Load Systems
E-commerce, Fintech, Media
E-commerce, ERP, Media
Embedded, Mobile, Telecom
E-commerce, Internet of Things, Medtech
High Load Systems, Media, Mobile
High Load Systems, Internet of Things, Legal
Data Science, Embedded, Machine Learning
Cloud Computing, Internet of Things, Machine Learning
E-commerce, Fintech, Insurance
Automotive, Mobile
Fintech, Logistics, Medtech
Data Science, GameDev, Media
AR/VR, Automotive, Media
ERP, Logistics, Manufacturing
E-commerce, Embedded, Mobile
Embedded, Hardware, Logistics
Data Science, Machine Learning, Mobile
Fintech, Media, Travel
Automotive, ERP
Automotive, Fintech, Logistics
E-commerce, Security, Travel
Big Data, Data Science, Security
Telecom, Інша
AR/VR, Інша
AR/VR, Fintech, Mobile
Fintech, Hardware, Logistics
GameDev, Media, Інша
Blockchain, E-commerce
Adtech, Gambling, GameDev
Fintech, Media, Medtech
Blockchain, Logistics
Internet of Things, Logistics, Robotics
Cloud Computing, Medtech, Mobile
E-commerce, Fintech, Logistics
Manufacturing, Media, Mobile
Automotive, Media
Fintech, Mobile, Telecom
Automotive, Fintech, Інша
Big Data, Machine Learning, Manufacturing
Cloud Computing, Legal
Manufacturing, Mobile, Інша
Blockchain, ERP
E-commerce, Machine Learning, Media
Adtech, Embedded, Medtech
Fintech, Gambling, High Load Systems
AR/VR, Machine Learning, Mobile
Edtech, Legal, Інша
Big Data, Cloud Computing, Fintech
Fintech, Gambling, Інша
Cloud Computing, ERP, Telecom
Geospatial, High Load Systems
GameDev, High Load Systems, Media
Machine Learning, Mobile, Інша
E-commerce, ERP, Travel
Cloud Computing, Manufacturing
GameDev, Medtech
E-commerce, Logistics, Telecom
Cloud Computing, Machine Learning, Media
Adtech, Medtech
Cloud Computing, Mobile, Security
Internet of Things, Machine Learning, Robotics
Blockchain, Fintech, Інша
Logistics, Manufacturing, Mobile
Adtech, Embedded, Media
AR/VR, Automotive
Agriculture, Mobile
Adtech, Fintech, Media
Logistics, Medtech, Mobile
AR/VR, Data Science, E-commerce
Adtech, Big Data, Fintech
Automotive, E-commerce, Insurance
E-commerce, Medtech, Інша
Fintech, Insurance, Travel
Fintech, Geospatial, Insurance
Adtech, Mobile, Інша
ERP, Logistics
High Load Systems, Manufacturing, Medtech
E-commerce, GameDev, Media
Medtech, Robotics, Інша
Automotive, Robotics, Security
Fintech, GameDev, Mobile
AR/VR, Data Science, Internet of Things
Cloud Computing, High Load Systems, Legal
Fintech, Internet of Things
Logistics, Travel, Інша
Data Science, Інша
Big Data, Gambling, Mobile
E-commerce, GameDev
Blockchain, E-commerce, Manufacturing
Big Data, Machine Learning, Mobile
GameDev, Media
Cloud Computing, Data Science, E-commerce
Automotive, High Load Systems, Logistics
Manufacturing, Security
Adtech, GameDev, Media
Logistics, Media, Medtech
ERP, High Load Systems
GameDev, Travel
E-commerce, ERP, Machine Learning
E-commerce, Fintech, High Load Systems
ERP, Insurance
Big Data, Cloud Computing, Mobile
Mobile, Telecom, Інша
E-commerce, Security, Інша
ERP, Telecom, Інша
Media, Telecom, Інша
Fintech, Logistics, Travel
Data Science, Logistics, Інша
Big Data, Insurance, Internet of Things
AR/VR, Manufacturing
Agriculture, Fintech, Security
Embedded, Geospatial, Logistics
E-commerce, Logistics, Manufacturing
Adtech, Internet of Things
Embedded, Medtech, Robotics
Automotive, Insurance, Інша
ERP, Legal, Security
E-commerce, Edtech, Fintech
Machine Learning, Manufacturing
Mobile, Uberfication
Data Science, Legal
Cloud Computing, Data Science, Mobile
Data Science, Edtech, Machine Learning
Cloud Computing, E-commerce, Інша
Big Data, Fintech, Legal
Edtech, Fintech
Big Data, Cloud Computing, Robotics
AR/VR, Data Science
Hardware, Media, Telecom
Internet of Things, Medtech, Telecom
Machine Learning, Uberfication
Data Science, Internet of Things, Інша
ERP, High Load Systems, Travel
Internet of Things, Media, Інша
Embedded, Security
Data Science, Hardware, Telecom

### Company type

In [3082]:
print('company_type',df2020['company_type'].unique())
print("\n")
print('company_type',df2021['company_type'].unique())
print("\n")
print('company_type',df2022['company_type'].unique())
print("\n")
print('company_type',df2023['company_type'].unique())
print("\n")
print('company_type',df2024['company_type'].unique())
print("\n")

company_type ['Аутсорсингова' 'Продуктова' 'Інша' 'Стартап' 'Аутстафінгова']


company_type ['Аутсорсингова' 'Продуктова' 'Інша' 'Стартап' 'Аутстафінгова']


company_type ['Стартап' 'Продуктова' 'Аутсорсингова' 'Аутстафінгова' 'Інша' 'Фріланс']


company_type ['Сервісна (аутсорсингова)' 'Продуктова'
 'Державне підприємство / установа' 'Аутстафінгова' 'Стартап' 'Інша'
 'Фриланс']


company_type ['Сервісна (аутсорсингова)' 'Продуктова'
 'Державне підприємство / установа' 'Аутстафінгова' 'Стартап' 'Інша'
 'Фриланс']

In [3083]:
df2022['company_type'] = df2022['company_type'].replace({'Фріланс': 'Фриланс'})
df2023['company_type'] = df2023['company_type'].replace({'Сервісна (аутсорсингова)': 'Аутсорсингова'})
df2024['company_type'] = df2024['company_type'].replace({'Сервісна (аутсорсингова)': 'Аутсорсингова'})

### Number of employees

In [3084]:
print('number_of_employees',df2020['number_of_employees'].unique())
print("\n")

print('number_of_employees',df2021['number_of_employees'].unique())
print("\n")

number_of_employees ['до 1000' 'понад 1000' 'Лише я' 'до 50' 'до 10 спеціалістів' 'до 200']


number_of_employees ['до 50' 'до 200' 'до 1000' 'понад 1000' 'до 10 спеціалістів' 'Лише я']

### Bonus

In [3085]:
print([float(f) for f in df2020['bonus'].unique() if pd.notna(f)])
print("\n")
print('bonus',df2021['bonus'].unique())

[4000.0, 1000.0, 1100.0, 30000.0, 0.0, 100.0, 500.0, 2000.0, 200.0, 5000.0, 11500.0, 3000.0, 1500.0, 800.0, 10000.0, 75.0, 7000.0, 50.0, 900.0, 6300.0, 6500.0, 3600.0, 150.0, 2500.0, 750.0, 6100.0, 35.0, 15000.0, 10600.0, 8000.0, 5700.0, 400.0, 600.0, 300.0, 6000.0, 9000.0, 70.0, 475.0, 250.0, 20000.0, 25000.0, 4800.0, 5750.0, 2850.0, 3500.0, 13500.0, 1900.0, 2200.0, 4500.0, 5500.0, 2250.0, 12000.0, 1300.0, 30.0, 1600.0, 450.0, 700.0, 4870.0, 1200.0, 19000.0, 1650.0, 60.0, 285.0, 770.0, 6400.0, 6700.0, 1275.0, 130.0, 1400.0, 45.0, 5900.0, 280.0, 6057.0, 3400.0, 2400.0, 9500.0, 190.0, 90.0, 350.0, 330.0, 302.0, 950.0, 6200.0, 550.0, 1850.0, 1995.0, 4300.0, 850.0, 3200.0, 4200.0, 8200.0, 3700.0, 180.0, 1120.0, 1800.0, 260.0, 177.0, 2800.0, 210.0, 25.0, 266.0, 1700.0, 570.0, 100000.0, 36000.0, 1750.0, 2160.0, 380.0, 3100.0, 575.0, 4560.0, 460.0, 3800.0, 11000.0, 86.0, 7500.0, 15.0, 2700.0, 855.0, 360.0, 8500.0, 485.0, 3300.0, 2650.0, 80.0, 7800.0, 2100.0, 270.0, 160.0, 240.0, 15600.0, 81.0, 95.0, 875.0, 140.0, 235.0, 18000.0, 2560.0, 2300.0, 225.0, 157.0, 690.0, 3050.0, 212.0, 7200.0, 120.0, 650.0, 1150.0, 142.0, 40.0, 1.0, 9400.0, 520.0, 2900.0, 230.0, 780.0, 196.0, 970.0, 1250.0, 175.0, 170.0, 680.0, 110.0, 2470.0, 560.0, 33.0, 1333.0, 96.0, 320.0, 163.0, 760.0, 44.0, 228.0, 2230.0, 20.0, 2350.0, 1490.0, 2137.0, 3215.0, 167.0, 158.0, 2475.0, 514.0, 470.0, 530.0, 5400.0, 5850.0, 1630.0, 124.0, 135.0, 1050.0, 3150.0, 88.0, 220.0, 13000.0, 1188.0, 198.0, 290.0, 1690.0, 555.0, 3750.0, 709.0, 26000.0, 458.0, 2805.0, 2600.0, 87.0, 10.0, 660.0, 277.0, 390.0, 38.0, 98.0, 1350.0, 16000.0, 540.0, 17.0, 144.0, 125.0, 57000.0, 444.0, 5.0]


bonus ['300' nan '400' '1577' '50' '200' '1000' '2700' '10000' '490' '2000' '95'
 '1500' '1800' '600' '3000' '72' '90' '5000' '1150' '35000' '150' '500'
 '9500' '100' '800' '190' '30' '155' '700' '60' '1400' '850' '250' '4500'
 '170' '18' '20000' '1300' '184' '1200' '110' '750' '3200' '6000' '3500'
 '2500' '3300' '3600' '40' '180' '13400' '650' '1700' '7000' '450' '6600'
 '5500' '12000' '900' '80' '4600' '4000' '23000' '1100' '8000' '350'
 '30000' '24000' '1425' '550' '6400' '70' '2600' '1750' '4700' '65' '3100'
 '133' '7800' '2375' '6500' '14000' '1900' '3750' '20' '2200' '11400' '86'
 '6700' '3800' '2800' '7600' '16000' '2400' '34' '475' '1600' '14250'
 '285' '126' '847' '2100' '950' '75' '840' '1270' '240' '230' '2185'
 '19200' '45' '140' '330' '567' '35' '680' '13000' '9315' '270' '4750'
 '120' '17000' '25' '9000' '185' '28000' '42000' '3650' '17' '10500'
 '2632' '10' '3648' '130' '280' '15000' '50000' '15' '52' '1650' '261'
 '6750' '2250' '7500' '142,5' '220' '195' '560' '186' '160' '4250' '4200'
 '260' '60000' '72000' '910' '70000' '275' '364' '11000' '730' '54' '630'
 '1450' '132' '1904' '380' '570' '76' '62' '1424' '77' '460' '85' '340'
 '1174' '37' '1250' '5100' '4800' '25500' '0' '18000' '8550' '5700' '825'
 '7100' '3700' '40000' '5652' '6650' '25000' '1420' '6450' '12800' '6250'
 '2820' '19000' '6200' '7200' '5800' '5600' '1375' '5400' '5300' '4300'
 '4150' '1880' '540' '9170' '100000' '625' '8500' '1140' '4900' '2327'
 '1120' '4350' '4225' '620' '8300' '2300' '320' '2750' '615' '665' '1350'
 '3534' '3400' '3325' '10650' '430' '2900' '56' '855' '2625' '135' '1850'
 '660' '142' '4585' '2850' '310' '510' '13' '470' '368' '175' '227' '370'
 '28' '152' '780' '542' '480' '14' '33']

In [3086]:
df2020['bonus'] = df2020['bonus'].astype('Int64')

df2021['bonus'] = (
    df2021['bonus']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .replace('nan', None)
    .astype(float)
    .round()
    .astype('Int64')
)

### Salary change

In [3087]:
print('salary_change',df2020['salary_change'].unique())
print("\n")
print('salary_change',df2021['salary_change'].unique())
print("\n")

salary_change ['-1520' '5000' '1000' '100' '3700' '5500' '-1000' '0' '200' '500' '2000'
 '3000' '3500' '1600' '1300' '2300' '600' '$500' '1425' '1500' '1200'
 '-400' '7000' '50' '1400' '300' '2500' '6200' '-2500' '1100' '900' '336'
 '750' '550' '-500' '-3000' '830' '700' '35' '-1200' '1620' '665' '400'
 '1700' '800' '-600' '950' '-200' '150' '250' '1140' '-700' '-300' '475'
 '2200' '-' nan '-2000' '2400' '1250' '350' '285' '451.25' '540' '1235'
 '815' '1800' '-1400' '1550' '_' '+100$' '500$' '$380' '380' '-800' '-20'
 '450' '535' '1450' '-370' '$300' '9' '160' '1390' '1135' '430' '120'
 '110' 'Не как ' '140' '270' 'не изменилась' 'ds' '290' '1150' '660' '650'
 '213' 'была 450, сейчас 770' '2100' '260' '2750' '1900' '330' '1005'
 '420' '185' '-137' '150$' '225$' '741' '170' '-100' '1141' '70' '385'
 '75' '245' '980' '210' '1350' '135' '280' '-440' 'зросла на 150' '1370'
 '220' '570' '-2200' '1750' '1375' '340' '$200' '190' '-250' 'Я 1200'
 '-1800' 'работаю пол года, пересмотр сказали через год' '80' '180' '60'
 '95' '4100' 'o' '585' '446' '2046' '30' '176' '126' '970' '-108' '373'
 '-192' '6000' '-50' 'Не змінилася ' 'не працюю ще 12 місяців' '-175'
 '332' '$100' '2150' '...' '215' '1500- 1700' '-30' '2370' '148' '-1500'
 '1' '840' '560' '360' '1050' '4500' '620' '30%' '1640' '1520' '1200$'
 '2800' '90' '2700' '760' '1850' 'не змінилась' '230' '325' '414' '640'
 '-450' 'зменшилась на 200' '271' 'Не змінилась' '-350' '-750' '850' '375'
 '40' '3300' '195' '---' '460' '494' '72' '1420' '1950' '1095' '3450'
 'Не змiнилась' '4000' '10' '$1000' '2915' '15%' '860' '320' '520$' '-150'
 'Отработала только 3 месяца'
 'Было 2000 вместе с бонусами, теперь ставка 1500' '522' '53' '530' '172'
 '630' 'На 400' '240' '+300$' '20' '0 через фріз на карантині' '655'
 '1770' 'ніяк' '+1400$' '480' '2350' '3550' '725' '1680' '2850' '2260'
 'никак' '242' '1075' '125' '-900' '1260' '2600' '-335' '17' '217'
 'Не изменилась' '820' '$400' 'Не змінилася' 'не змінилася'
 'була 1500 стала 2500' '1190' 'больше на $50' '1025' '575' '300$' '2'
 '465' '675' '520' 'Защитилась однаков' 'Нічого не змінилось' '261' '1042'
 '1630' '931' '155' '1230' '572' '735' '825' '415' '720' 'стала больше'
 'не змiнилась' 'З00' 'На 300usd' '321' '509' '130' '163'
 'В 5 раз выросла ' '395' '615' '-110' '485' '1485' '45' '-170' '785'
 '510' '353' '789' 'Зросла на 300' 'Не изменилась ' '790' '427' '1310'
 'зросла на 400' '310' '390' '-140' '600-950' '1070' '940' '1010'
 'пока никак' 'Пересмотр еще не произошёл' 'никак ( ' '335' '192' '610'
 'зросла на $50' '865' '178' '457' '680' '425' '588' '1085'
 'На 200$ збільшилась' 'Так' '309' '780' '-396' '565' '670' '-1300' '555'
 '590' '-120' '200$' '100$' 'ніяк не змінилася' '814' '165' '696' '57'
 '235' '-204' '+250$' 'зменшилась через фріланс' '144' '105'
 "З'явилась можливість отримати додаткові бонуси" '175' '275' '25' '212'
 '107' '915' '-130' '-111' '685' '0,85' '3600' '92' '209' 'на 200$' '106'
 '100-150' '265' '2280' '440' 'Ні'
 'була $800 фултайм, стала $750 - парттайм' '227' '370' '470' '65' '77'
 '810' 'не змінилась ' '366' '243' '603' 'Стала меньше на 100' '3' '562'
 '-40' '254' 'працюю меньше 12 місяців' '-60' 'Не змінилась ' '-215' '225'
 'Жодним чином' '-1100' '12300' '10000' '444' '-35' 'перша зарплата' '36'
 '0,018' '15' '214' '-2100' 'Поки не змінювалась' 'сложно сказать'
 '+- 20$']


salary_change ['350' '200' '0' '600' '1500' '300' '650' '285' '850' '400' '333' '500'
 '700' '1000' '1100' '3000' '240' '1300' '450' '150' '1417' '800' '960'
 '250' '225' '1200' '100' '675' '181' '-25' '50' '370' '664' '2000' '550'
 '750' '2500' '3500' '2200' '3200' '4000' '715' '-500' '69' '1800' '640'
 '1400' '185' '900' '830' '1700' '75' '280' nan '1250' '727' '940' '170'
 '180' '368' '380' '730' '4500' '950' '5400' '-1000' '1070' '-200' '2100'
 '1600' '470' '5000' '2400' '2700' '2300' '125' '3300' '260' '1850' '425'
 '-300' '480' '4100' '95' '1050' '222' '690' '375' '1900' '120' '1750'
 '-1500' '160' '2640' '1040' '1150' '110' '6000' '190' '530' '130' '73'
 '10' '475' '74' '-50' '60' '-100' '2800' '575' '-4000' '4300' '2820'
 '5500' '780' '3900' '3400' '313' '920' '1520' '620' '1125' '179' '570'
 '2495' '770' '332' '1350' '740' '440' '1461' '890' '2350' '-150' '2150'
 '70' '4400' '2900' '1950' '290' '360' '990' '340' '2600' '366' '1425'
 '820' '405' '1060' '670' '460' '146' '140' '-700' '7000' '520' '522'
 '-1160' '8000' '564' '1380' '665' '1285' '2750' '2250' '1970' '1650'
 '2770' '1450' '80' '980' '1430' '840' '210' '420' '330' '870' '90' '1120'
 '825' '115' '1375' '580' '-250' '755' '320' '-1100' '-600' '310' '1020'
 '-450' '288' '590' '20' '63' '25' '560' '395' '-800' '97' '111' '1235'
 '-157' '815' '1287' '547' '880' '-900' '145' '317' '875' '-1200' '720'
 '769' '295' '66' '-35' '546' '265' '230' '270' '-2500' '477' '1185' '864'
 '630' '10000' '-135' '165' '905' '1619' '77' '322' '40' '24' '175' '220'
 '1270' '314' '1550' '2010' '291' '3600' '3325' '985' '30' '-400' '2650'
 '1072' '4800' '484' '9000' '55' '2039' '1209' '525' '-2000' '625' '215'
 '999' '790' '2135' '534' '674' '1108' '-60' '610' '1333' '352' '771'
 '5600' '9250' '5530' '13000' '5800' '3700' '6500' '2520' '3800' '1725'
 '1190' '3920' '+1500$' '2080' '3100' '5450' '4700' '2490' '2125' '1625'
 '2373' '-30' '3660' '2739' '3021' '871' '+4700$' '1590' '2826' '2175'
 '2220' '1093' '2550' '1866' '1490' '1426' '2620' 'було 4 стало 6' '4512'
 '987' '1615' '1670' '442' '1710' '1326' '3350' '1995' '3490' '4200'
 '2335' '2897' '1880' '1575' '1940' '1140' '2375' '2825' 'x2' '485' '455'
 '390' '631' '2075' '2425' 'В 4 рази' '-5000' '2170' '2193' '384' '805'
 '1440' '1275' '775' '2025' '$1,000' '342' '2410' '1830'
 'Збільшилась в три рази після зміни робочого місця ' '1,700$' '1,200$'
 '$1,200' '3450' '1890' '3145' '1,000$' '2,000$' '1110' '760' '663' '660'
 '465' '877' '335' '1330' '2450' '1095' '1770' '2824' '2325' '1325' '1420'
 '266' '3250' '646' '1435' 'Не изменилась' 'Зросла' '$900' '1280' '1840'
 '-650' '1,500$' '1555' '1220' '1663' '1760' '1565' '2510' 'Не как'
 'На 1000' '+$1700' '1637' 'не было работы 8 лет' 'Была $1500 стала $2500'
 '1875' '1225' '655' '2040' '1320' '1115' '+1100$' '385' '107'
 'Виросла в 1,5 рази' '+$400' '18.май' '1340' '1230' '1265' '454'
 'Не змінилась' '930' '540' '1135' '-' '1260' '725' '227' '578' '855'
 '387' '1,050$' '975' '1372' '£1300$' '635' '557' '±900' '1025'
 'уменьшилась из-за смены специализации' '$500' '30%'
 'Розумію, що тут треба написати тільки цифру. Але опишу всю історію. Прийшла на стажування за 350, потім було підвищення 400, 500, далі 800. І ось останнє влітку -- 1100. '
 'з 0 до 1100)' '400-600-1100' '472' '695' '200 => 900' '+400$' '275'
 'с 200 до 800' 'Работаю меньше 12 месяцев ;)' '174'
 'Працюю розробником перший місяць' 'Працюю менше 12 місяців' '×2' '-770'
 '—400' '615' '612' '3' '388' 'еще нет' '212'
 'я свитчер. на прошлой работе выходило около $900-1000 в месяц (АСУ ТП). сейчас после смены направления естсествеено упала до 500'
 'Працю менше 12 місяців' '_' '499' 'Не змінилася' '-350' '150$'
 'any changes']

In [3088]:
def extract_numeric(val):
    if isinstance(val, str):
        val = val.replace(',', '.').replace('$', '').replace('%', '').strip()
        if val.startswith('+'):
            val = val[1:]
        try:
            return float(val)
        except:
            return None
    return val

df2020['salary_change'] = df2020['salary_change'].apply(extract_numeric)
df2021['salary_change'] = df2021['salary_change'].apply(extract_numeric)

### Title

In [3089]:
print('title',df2020['title'].unique())
print("\n")
print('title',df2021['title'].unique())
print("\n")
print('title',df2022['title'].unique())
print("\n")
print('title',df2023['title'].unique())
print("\n")
print('title',df2024['title'].unique())
print("\n")

title [nan 'Senior' 'Middle' 'Junior' 'Tech Lead' 'Intern/Trainee' 'Head'
 'Team Lead' 'Architect' 'Manager']


title ['Middle' 'Junior' 'Senior' nan 'Head' 'Intern/Trainee' 'Team Lead'
 'Manager' 'Tech Lead' 'Architect']


title ['Team Lead' 'Middle' 'Junior' 'Senior' 'Tech Lead' 'Intern/Trainee'
 'Немає тайтлу' 'Manager' 'Architect' 'Head']


title ['Middle' 'Head' None 'Senior' 'Tech Lead' 'Junior' 'Intern/Trainee'
 'Architect']


title ['Middle' 'Head' None 'Senior' 'Tech Lead' 'Junior' 'Intern/Trainee'
 'Architect']

In [3090]:
df2022['title'] = df2022['title'].replace({'Немає тайтлу': np.nan})
df2023['title'] = df2023['title'].replace({None: np.nan})
df2024['title'] = df2024['title'].replace({None: np.nan})

### Region

In [3091]:
print("region", df2020['region'].unique())
print("\n")
print("region", df2021['region'].unique())
print("\n")
print("region", df2022['region'].unique())
print("\n")
print("region", df2023['region'].unique())
print("\n")
print("region", df2024['region'].unique())
print("\n")

region ['Київ' 'Дніпро' 'Львів' 'Харків' 'Інше' 'Одеса' 'Тернопіль' 'Не Україна'
 'Чернівці' 'Вінниця' 'Івано-Франківськ' 'Запоріжжя' 'Миколаїв' 'Херсон'
 'Житомир' 'Чернігів' 'Кривий Ріг' 'Ужгород' 'Рівне' 'Хмельницький'
 'Маріуполь' 'Суми' 'Черкаси' 'Полтава' 'Луцьк' 'Кропивницький']


region ['Харків' 'Київ' 'Черкаси' 'Суми' 'Дніпро' 'Рівне' 'Інше' 'Львів' 'Одеса'
 'Вінниця' 'Миколаїв' 'Івано-Франківськ' 'Хмельницький' 'Луцьк'
 'Запоріжжя' 'Тернопіль' 'Чернігів' 'Чернівці' 'Кривий Ріг'
 'Кропивницький' 'Полтава' 'Маріуполь' 'Житомир' 'Херсон' 'Ужгород']


region ['Івано-Франківськ' 'Не Україна' 'Київ' 'Львів' 'Житомир' 'Дніпро'
 'Тернопіль' 'Вінниця' 'Кропивницький' 'Чернігів' 'Харків' 'Рівне'
 'Запоріжжя' 'Суми' 'Чернівці' 'Одеса' 'Черкаси' 'Полтава' 'Хмельницький'
 'Миколаїв' 'Херсон']


region ['Львів' 'Київ' 'Хмельницький' 'Не Україна' 'Харків' 'Миколаїв' 'Вінниця'
 'Житомир' 'Чернівці' 'Одеса' 'Суми' 'Тернопіль' 'Кропивницький' 'Дніпро'
 'Рівне' 'Івано-Франківськ' 'Полтава' 'Запоріжжя' 'Чернігів' 'Черкаси'
 'Херсон']


region ['Львів' 'Київ' 'Хмельницький' 'Не Україна' 'Харків' 'Миколаїв' 'Вінниця'
 'Житомир' 'Чернівці' 'Одеса' 'Суми' 'Тернопіль' 'Кропивницький' 'Дніпро'
 'Рівне' 'Івано-Франківськ' 'Полтава' 'Запоріжжя' 'Чернігів' 'Черкаси'
 'Херсон']

In [3092]:
df2020['region'] = df2020['region'].replace({'Інше': 'Не Україна'})

### Worksite

In [3093]:
print("work_site",df2020['work_site'].unique())
print("\n")
print("work_site",df2021['work_site'].unique())
print("\n")

work_site ['Віддалено' 'Частково віддалено, частково в офісі' 'В офісі' nan]


work_site ['Частково віддалено, частково в офісі' 'В офісі' 'Віддалено' nan]

### Education

In [3094]:
print('education', df2020['education'].unique())
print("\n")
print('education', df2021['education'].unique())
print("\n")
print('education', df2022['education'].unique())
print("\n")

education ['Вища' 'Дві вищих' 'Середня' 'Кандидат наук' 'Ще студент']


education ['Вища (бакалавр, спеціаліст, магістр)' 'Ще студент вишу' 'Середня'
 'Середня спеціальна' 'Дві вищі']


education ['Вища (бакалавр, спеціаліст, магістр)' 'Ще студент вишу'
 'Середня спеціальна' 'Середня' 'Дві вищі']

In [3095]:
df2021['education'] = df2021['education'].replace({'Вища (бакалавр, спеціаліст, магістр)': 'Вища'})
df2022['education'] = df2022['education'].replace({'Вища (бакалавр, спеціаліст, магістр)': 'Вища'})

df2020['education'] = df2020['education'].replace({'Ще студент вишу': 'Студент'})
df2021['education'] = df2021['education'].replace({'Ще студент вишу': 'Студент'})
df2022['education'] = df2022['education'].replace({'Ще студент вишу': 'Студент'})

df2020['phd'] = df2020['education'].apply(lambda x: 'Кандидат наук' if x == 'Кандидат наук' else "Немає")
df2020['education'] = df2020['education'].apply(lambda x: np.nan if x == "Кандидат наук" else x)

### University

In [3096]:
print("university",df2020['university'].unique())
print("\n")

university ['НТУУ «КПІ»' 'ХНУРЕ' 'КНУБА' nan 'НУ «Львівська політехніка»' 'Інший виш'
 'ВНТУ' 'ЛНУ ім. Франка' 'ОНУ ім. Мечникова' 'КНУ ім. Шевченка' 'НаУКМА'
 'НУХТ' 'КНЕУ' 'ДНУ ім. Гончара' 'ДонНУ ім. Василя Стуса' 'НАУ' 'ХНЕУ'
 'ХАІ' 'НТУ «Дніпровська політехніка»' 'ОНПУ' 'СумДУ' 'ЧНУ ім. Федьковича'
 'ХНУ ім. Каразіна' 'ВНУ ім. Даля' 'ДонНТУ' 'НТУ «ХПІ»' 'КНУТД' 'ЧНТУ'
 'НУК ім. Макарова' 'НМетАУ' 'ЖДТУ' 'ОНАЗ ім. Попова'
 'ХНУ [м. Хмельницький]' 'ДУТ' 'ДНУЗТ' 'ЗНТУ' 'УКУ' 'ЧНУ ім. Петра Могили'
 'ЦНТУ [м. Кропивницький]']

### Position

In [3097]:
print("position",df2020['position'].unique())
print("\n")
print("position",df2021['position'].unique())
print("\n")
print("position",df2022['position'].unique())
print("\n")
print("position",df2023['position'].unique())
print("\n")
print("position",df2024['position'].unique())
print("\n")

position ['Support'
 'Software Engineer (Junior, Middle, Senior, Team/Tech Lead, Architect)'
 'Project/Product/Program Manager, Product Owner, Scrum Master, Delivery Manager'
 'Data Science, Machine Learning, Big Data'
 'QA Engineer (Junior, Middle, Senior, Team/Tech Lead, Manager)'
 'DevOps, SysAdmin' 'HR' 'Analyst (Business, Data, System)' 'Designer'
 'HTML Coder' 'Customer Success' 'Security Specialist' 'Sales Manager'
 'Marketing, SEO, Copywriter' 'DBA'
 'СTO, Director of Engineering, Program Director' 'Technical writer'
 'ERP/CRM']


position ['Marketing, SEO, Copywriter' 'HR'
 'Project/Product/Program Manager, Product Owner, Scrum Master, Delivery Manager'
 'DevOps, SysAdmin'
 'СTO, Director of Engineering, Program Director, CEO, (co-)founder'
 'QA Engineer (Junior, Middle, Senior, Team/Tech Lead, Manager)'
 'Designer' 'Analyst (Business, Data, System)'
 'Data Science, Machine Learning, Big Data' 'Sales Manager' 'DBA'
 'Security Specialist' 'HTML Coder' 'Support' 'ERP/CRM'
 'Hardware Engineer' 'Technical writer' 'Customer Success'
 'Software Engineer (Junior, Middle, Senior, Team/Tech Lead, Architect)']


position ['Designer / Artist (Graphic, UX/UI, Game, Artist, Sound etc.)'
 'Software Engineer (Junior, Middle, Senior, Team/Tech Lead, Architect)'
 'QA Engineer (Junior, Middle, Senior, Team/Tech Lead, Manager)'
 'Data Science, Machine Learning, Big Data'
 'Analyst (Business, Data, System)' 'Sales Manager' 'HTML Coder'
 'Game Developer / Programmer'
 'Project/Product/Program Manager, Product Owner, Scrum Master, Delivery Manager'
 'DevOps, SRE' 'Marketing, SEO, Copywriter' 'HR/Recruiter' 'Support'
 'SysAdmin' 'Security Specialist'
 'СTO, Director of Engineering, Program Director, CEO, (co-)founder'
 'Customer Success' 'DBA' 'Technical writer' 'ERP/CRM' 'Hardware Engineer'
 'Legal']


position ['Manual QA' 'Head of QA' 'Automation QA / AQA'
 'Software Engineer / Software Developer'
 'SRE (Site Reliability Engineer)' 'General QA' 'Product Designer'
 'Lead Generation Specialist' 'Director of Engineering'
 'Head of Operations' 'Product Owner (у продакт менеджменті)'
 'HR Manager / HR specialist'
 'Recruiter / Recruitment Specialist / Technical Recruiter'
 'Customer Success Manager' 'Project Manager' 'Infrastructure Engineer'
 'Marketing Data Analyst / Marketing Analyst' 'DevOps Engineer'
 'UI/UX Researcher' 'Data Analyst' 'Product Manager'
 'BA (Business Analyst)' 'Product Analyst'
 'Content Manager / Content Marketing Manager' 'ML Engineer'
 'Head of Analytics' 'Nous Technology Group' 'PPC Specialist'
 'AI Engineer' 'Delivery Manager' 'Research Scientist' 'Community Manager'
 'Product Marketing Manager' 'Data Scientist'
 'Talent Acquisition Manager/Talent Acquisition Specialist'
 'Head of Product Design' 'UI/UX Designer'
 'Learning and Development / Training and Development' 'Head of Delivery'
 'Procurement' 'Head of Engineering' 'Software Architect' 'Scrum Master'
 'Financial Analyst' 'Information security specialist' 'SysAdmin'
 'Data Engineer / Big Data Engineer' 'Business Development Manager'
 'Customer Support' 'Operations Director' 'HR Business Partner'
 'Head of HR' 'SMM (Social Media Manager)' 'Data Quality Engineer'
 'Technical Support' 'Product Director'
 'SDET (Software Development Engineer in Test)' 'Engineering Manager'
 'Head of Support'
 'Marketing Project Manager / Marketing operations manager'
 'Computer Vision Engineer' 'Security Engineer' 'Copywriter'
 'CEO / founder / cofounder' 'Security Analyst / SOC Analyst'
 'Network Engineer' 'HR People Partner' 'Sales manager / Sales Executive'
 'CTO (Chief Technology Officer) / Technical Director'
 'Head of Frontend & QA' 'System Architect' 'Marketing Manager'
 'Program Manager' 'Performance Marketing Manager' 'Game Producer'
 'Concept Artist'
 'Finance Manager / Financial Manager / Financial controller'
 'Executive Director' 'Content Writer' 'TechOps Engineer'
 'Motion Designer' 'Billing Operations Specialist' 'Performance QA'
 'Creative Director' 'Technical Project Manager'
 'HR Operations Specialist / People Operations Specialist' 'HR Generalist'
 '2D Artist' 'Solution Architect' 'PR Manager' 'Partnership manager'
 'CPO (Chief Product Officer)' 'BI Analyst' 'Image Quality Engineer'
 'CMO (Chief Marketing Officer)' 'Operations Manager' 'Head of SRE'
 'Sales Development Representative' 'Technical writer' 'NOC Engineer'
 'Compliance Manager' 'Project Coordinator' 'ERP/CRM Consultant'
 'Talent Sourcer / Talent Researcher / Recruitment Researcher'
 'Head of Product' 'Head of R&D' 'HR Director (HRD)' 'Embedded QA'
 'Cloud Architect' 'Graphic Designer' 'COO (Chief Operating Officer)'
 'Digital Marketing Manager' 'UI/UX Writer' 'Accountant'
 'Employer Brand Manager' 'Delivery Director' 'Legal Counsel'
 'VP of Engineering' 'SOC Engineer / SecOps Engineer'
 'Marketing Program Manager' 'Integrations Engineer / Integration Manager'
 'System Analyst' 'Head of Marketing' 'Brand Communications Manager'
 'Cloud Engineer' 'Hardware Engineer' 'Configurator'
 'Administrative Manager' 'Head of BA Office' 'Ethereum security auditor'
 'R&D Manager' '3D Artist' 'Level Designer' 'BI Engineer'
 'DBA (Database administrator)' 'Head of Legal' 'Linkbuilder'
 'Account Manager / Account Executive' 'Animator 3D' 'Resource Manager'
 'Cybersecurity Engineer'
 'Office Manager / Office Administrator / Office Coordinator'
 'Mechanical Design Engineer' 'IT Director' 'Head of Customer Support'
 'Head of User Acquisition' 'Game Designer' 'SEO Specialist'
 'Application security engineer' 'Research Engineer'
 'Technical Game Designer' 'QA manager' 'Tech Consultant'
 'Database Engineer' 'Head of Talent Acquisition' 'Recruitment Assistant'
 'Creative Marketing Specialist' 'Personal officer' 'Finops team leader'
 'CBDO (Chief Business Development Officer)'
 'Product Owner (роль в скрамі)' 'Sales Assistant'
 'GPU Content validation' 'Lawyer' 'Penetration Tester' 'Technical Artist'
 'ASO Specialist / ASO Manager' 'Animator 2D' 'Head of Cloud'
 'Web Designer' 'Art Producer' 'Narrative Designer'
 'Manager of the Education Office' 'Head of Mobile'
 'Game Economy Designer' 'Technical Product Manager'
 'Communications Specialist' 'Release Manager' 'QA Manager'
 'Prototype Engineer' 'UI/UX Artist' 'VP of People Operations'
 'СIO (Chief information Officer)'
 'Email Marketing Specialist / E-mail Marketing specialist'
 'Administrative Assistant' 'Other' 'Head of Client Relations'
 'Brand Designer / Marketing Designer' 'QA Director' 'Operations Analyst'
 'Producer' 'Sound Designer' 'Head of PR'
 'Employee Engagement Manager /Employee experience Manager'
 'Head of Sales' 'Event Manager' 'CRM Manager' 'Software Analyst'
 'CHRO (Chief Human Resources Officer)' 'Application Architect'
 'Creative marketing specialist' 'Head of customer care (support+success)'
 'Data Labeling Specialist' 'HR Marketing Specialist'
 'Growth Marketing Manager / Growth Manager'
 'Talent Manager / Talent Partner' 'HR Coordinator' 'UI/UX Game Designer'
 'Data Architect' 'Head Of Content' 'Quality Architect'
 'Affiliate Manager' 'Sales Director' 'Anti-Fraud Analyst' 'Media Buyer'
 'Video editor' 'Game Mathematician' 'User Acquisition Manager'
 'Analytics Team Lead' 'Executive Assistant' 'Head of Administration'
 'Environment Artist' 'Helpdesk Engineer' 'Head of Data Science'
 'Retention Manager' 'Performance Analyst' 'Engineering manager'
 'Head of PPC' 'Head of Product Marketing' 'MLOps Engineer'
 'Head of Business Development' 'Integration Architect' 'Frontend'
 'Head of PMO' 'Program Director' 'Head of System Administration'
 'Head of Partnership' 'HR Analyst / People Analyst' 'Internal Auditor'
 'Design Generalist' 'Illustrator' 'Moderation team lead'
 'Cinematic Artist' 'Game AI Designer' 'Head of Digital Marketing'
 'Creative Producer' 'Research Analyst' 'Head of Communications'
 'Creative Marketing Manager' 'Chief Strategy Officer'
 'Head of Recruitment' 'Technical Animator' 'Head of Design'
 'Head of Retention' 'Game Analyst' 'Video Maker' 'VFX Artist'
 'Director of Product' 'Security Architect' 'Support'
 'Compensation and Benefit Specialist' 'HR Administrator'
 'Managing Director' 'Character Artist' 'CCO (Chief Commercial Officer)'
 'Marketing Director' 'Head of Learning and Development Department'
 'Head of Development' 'CLO (Chief Legal Officer)'
 'Engineering managerEngineering Manager' 'CFO (Chief Financial Officer)'
 'Market research specialist' 'Mail' 'Outreach Specialist'
 'Business Architect' 'Technical Producer' 'Cloud Solution Architect'
 'CAO (Chief Analytics Officer)' 'Business process development team lead'
 'Payment operations manager' 'Generalist Artist'
 'Influencer marketing manager' 'Moderation automation manager'
 'Head of Finance' 'Head of SMM' 'L&D Lead'
 'Client Partner / Engagement manager' 'System engineer'
 'Head of Customer Success' 'Reverse Engineer'
 'Head of Information Security' 'SAP consultant' 'Head of AI'
 'Data Collection specialist' 'VP of Product' 'P2P Specialist'
 'Drone Engineer / UAV Engineer / інженер БпЛА'
 'Chief Administrative Officer' 'Markup Developer'
 'Packaging Data Specialist' 'Team manager (cs:go)' 'Investment Analyst'
 'process manager' 'expert' 'IT Process Manager'
 'Director of Data Analytics' 'Traffic Manager'
 'Blockchain Security Auditor' 'Quality Assurance+Project Manager'
 'Head of Game Development' 'Microsoft Dynamics NAV' 'Country Manager'
 'Monitoring Specialist' 'Technical Designer' 'Head of Innovation'
 'Customer interaction capability manager' 'System Game Designer'
 'Automation Engineer' 'Quality control manager' 'Deep Learning Engineer'
 'FPGA Engineer' 'VP of Customer Success' 'Luxena' 'Test Architect'
 'Localization Manager' 'Head of CRM' 'Treasury Manager' 'Risk manager'
 'Web Analyst' 'Head of strategy and operations' 'Head of Affiliates'
 'Agile Coach' 'Graphic & Web designer' 'Head of Corporate Strategy'
 'Embedded Engineer' 'Product designer' 'Research Assistant'
 'Chief Managed Security Solutions Officer' 'NLP Engineer'
 'Cybersecurity consultant' 'D365 CRM Developer' 'Product Content Manager'
 'Solution ArchitectSoftware Engineer / Software Developer'
 'Head of compensation and benefits' 'Implementer' 'Gis'
 'Java Engineering Lead' 'Head of UX/UI' 'Head of SEO'
 'Electronics Engineer' 'Pre-Match Trader' 'anti-fraud' 'Quality Manager'
 'Network Security Engineer' 'Data Annotation Manager' 'VoIP Engineer'
 'Head of Risk Management' 'Designer Generalist' 'Onboarding manager'
 'Low-code engineer' 'Head of IT department' 'Application Administrator'
 'Quantitative researcher' 'Scriptwriter']


position ['Manual QA' 'Head of QA' 'Automation QA / AQA'
 'Software Engineer / Software Developer'
 'SRE (Site Reliability Engineer)' 'General QA' 'Product Designer'
 'Lead Generation Specialist' 'Director of Engineering'
 'Head of Operations' 'Product Owner (у продакт менеджменті)'
 'HR Manager / HR specialist'
 'Recruiter / Recruitment Specialist / Technical Recruiter'
 'Customer Success Manager' 'Project Manager' 'Infrastructure Engineer'
 'Marketing Data Analyst / Marketing Analyst' 'DevOps Engineer'
 'UI/UX Researcher' 'Data Analyst' 'Product Manager'
 'BA (Business Analyst)' 'Product Analyst'
 'Content Manager / Content Marketing Manager' 'ML Engineer'
 'Head of Analytics' 'Nous Technology Group' 'PPC Specialist'
 'AI Engineer' 'Delivery Manager' 'Research Scientist' 'Community Manager'
 'Product Marketing Manager' 'Data Scientist'
 'Talent Acquisition Manager/Talent Acquisition Specialist'
 'Head of Product Design' 'UI/UX Designer'
 'Learning and Development / Training and Development' 'Head of Delivery'
 'Procurement' 'Head of Engineering' 'Software Architect' 'Scrum Master'
 'Financial Analyst' 'Information security specialist' 'SysAdmin'
 'Data Engineer / Big Data Engineer' 'Business Development Manager'
 'Customer Support' 'Operations Director' 'HR Business Partner'
 'Head of HR' 'SMM (Social Media Manager)' 'Data Quality Engineer'
 'Technical Support' 'Product Director'
 'SDET (Software Development Engineer in Test)' 'Engineering Manager'
 'Head of Support'
 'Marketing Project Manager / Marketing operations manager'
 'Computer Vision Engineer' 'Security Engineer' 'Copywriter'
 'CEO / founder / cofounder' 'Security Analyst / SOC Analyst'
 'Network Engineer' 'HR People Partner' 'Sales manager / Sales Executive'
 'CTO (Chief Technology Officer) / Technical Director'
 'Head of Frontend & QA' 'System Architect' 'Marketing Manager'
 'Program Manager' 'Performance Marketing Manager' 'Game Producer'
 'Concept Artist'
 'Finance Manager / Financial Manager / Financial controller'
 'Executive Director' 'Content Writer' 'TechOps Engineer'
 'Motion Designer' 'Billing Operations Specialist' 'Performance QA'
 'Creative Director' 'Technical Project Manager'
 'HR Operations Specialist / People Operations Specialist' 'HR Generalist'
 '2D Artist' 'Solution Architect' 'PR Manager' 'Partnership manager'
 'CPO (Chief Product Officer)' 'BI Analyst' 'Image Quality Engineer'
 'CMO (Chief Marketing Officer)' 'Operations Manager' 'Head of SRE'
 'Sales Development Representative' 'Technical writer' 'NOC Engineer'
 'Compliance Manager' 'Project Coordinator' 'ERP/CRM Consultant'
 'Talent Sourcer / Talent Researcher / Recruitment Researcher'
 'Head of Product' 'Head of R&D' 'HR Director (HRD)' 'Embedded QA'
 'Cloud Architect' 'Graphic Designer' 'COO (Chief Operating Officer)'
 'Digital Marketing Manager' 'UI/UX Writer' 'Accountant'
 'Employer Brand Manager' 'Delivery Director' 'Legal Counsel'
 'VP of Engineering' 'SOC Engineer / SecOps Engineer'
 'Marketing Program Manager' 'Integrations Engineer / Integration Manager'
 'System Analyst' 'Head of Marketing' 'Brand Communications Manager'
 'Cloud Engineer' 'Hardware Engineer' 'Configurator'
 'Administrative Manager' 'Head of BA Office' 'Ethereum security auditor'
 'R&D Manager' '3D Artist' 'Level Designer' 'BI Engineer'
 'DBA (Database administrator)' 'Head of Legal' 'Linkbuilder'
 'Account Manager / Account Executive' 'Animator 3D' 'Resource Manager'
 'Cybersecurity Engineer'
 'Office Manager / Office Administrator / Office Coordinator'
 'Mechanical Design Engineer' 'IT Director' 'Head of Customer Support'
 'Head of User Acquisition' 'Game Designer' 'SEO Specialist'
 'Application security engineer' 'Research Engineer'
 'Technical Game Designer' 'QA manager' 'Tech Consultant'
 'Database Engineer' 'Head of Talent Acquisition' 'Recruitment Assistant'
 'Creative Marketing Specialist' 'Personal officer' 'Finops team leader'
 'CBDO (Chief Business Development Officer)'
 'Product Owner (роль в скрамі)' 'Sales Assistant'
 'GPU Content validation' 'Lawyer' 'Penetration Tester' 'Technical Artist'
 'ASO Specialist / ASO Manager' 'Animator 2D' 'Head of Cloud'
 'Web Designer' 'Art Producer' 'Narrative Designer'
 'Manager of the Education Office' 'Head of Mobile'
 'Game Economy Designer' 'Technical Product Manager'
 'Communications Specialist' 'Release Manager' 'QA Manager'
 'Prototype Engineer' 'UI/UX Artist' 'VP of People Operations'
 'СIO (Chief information Officer)'
 'Email Marketing Specialist / E-mail Marketing specialist'
 'Administrative Assistant' 'Other' 'Head of Client Relations'
 'Brand Designer / Marketing Designer' 'QA Director' 'Operations Analyst'
 'Producer' 'Sound Designer' 'Head of PR'
 'Employee Engagement Manager /Employee experience Manager'
 'Head of Sales' 'Event Manager' 'CRM Manager' 'Software Analyst'
 'CHRO (Chief Human Resources Officer)' 'Application Architect'
 'Creative marketing specialist' 'Head of customer care (support+success)'
 'Data Labeling Specialist' 'HR Marketing Specialist'
 'Growth Marketing Manager / Growth Manager'
 'Talent Manager / Talent Partner' 'HR Coordinator' 'UI/UX Game Designer'
 'Data Architect' 'Head Of Content' 'Quality Architect'
 'Affiliate Manager' 'Sales Director' 'Anti-Fraud Analyst' 'Media Buyer'
 'Video editor' 'Game Mathematician' 'User Acquisition Manager'
 'Analytics Team Lead' 'Executive Assistant' 'Head of Administration'
 'Environment Artist' 'Helpdesk Engineer' 'Head of Data Science'
 'Retention Manager' 'Performance Analyst' 'Engineering manager'
 'Head of PPC' 'Head of Product Marketing' 'MLOps Engineer'
 'Head of Business Development' 'Integration Architect' 'Frontend'
 'Head of PMO' 'Program Director' 'Head of System Administration'
 'Head of Partnership' 'HR Analyst / People Analyst' 'Internal Auditor'
 'Design Generalist' 'Illustrator' 'Moderation team lead'
 'Cinematic Artist' 'Game AI Designer' 'Head of Digital Marketing'
 'Creative Producer' 'Research Analyst' 'Head of Communications'
 'Creative Marketing Manager' 'Chief Strategy Officer'
 'Head of Recruitment' 'Technical Animator' 'Head of Design'
 'Head of Retention' 'Game Analyst' 'Video Maker' 'VFX Artist'
 'Director of Product' 'Security Architect' 'Support'
 'Compensation and Benefit Specialist' 'HR Administrator'
 'Managing Director' 'Character Artist' 'CCO (Chief Commercial Officer)'
 'Marketing Director' 'Head of Learning and Development Department'
 'Head of Development' 'CLO (Chief Legal Officer)'
 'Engineering managerEngineering Manager' 'CFO (Chief Financial Officer)'
 'Market research specialist' 'Mail' 'Outreach Specialist'
 'Business Architect' 'Technical Producer' 'Cloud Solution Architect'
 'CAO (Chief Analytics Officer)' 'Business process development team lead'
 'Payment operations manager' 'Generalist Artist'
 'Influencer marketing manager' 'Moderation automation manager'
 'Head of Finance' 'Head of SMM' 'L&D Lead'
 'Client Partner / Engagement manager' 'System engineer'
 'Head of Customer Success' 'Reverse Engineer'
 'Head of Information Security' 'SAP consultant' 'Head of AI'
 'Data Collection specialist' 'VP of Product' 'P2P Specialist'
 'Drone Engineer / UAV Engineer / інженер БпЛА'
 'Chief Administrative Officer' 'Markup Developer'
 'Packaging Data Specialist' 'Team manager (cs:go)' 'Investment Analyst'
 'process manager' 'expert' 'IT Process Manager'
 'Director of Data Analytics' 'Traffic Manager'
 'Blockchain Security Auditor' 'Quality Assurance+Project Manager'
 'Head of Game Development' 'Microsoft Dynamics NAV' 'Country Manager'
 'Monitoring Specialist' 'Technical Designer' 'Head of Innovation'
 'Customer interaction capability manager' 'System Game Designer'
 'Automation Engineer' 'Quality control manager' 'Deep Learning Engineer'
 'FPGA Engineer' 'VP of Customer Success' 'Luxena' 'Test Architect'
 'Localization Manager' 'Head of CRM' 'Treasury Manager' 'Risk manager'
 'Web Analyst' 'Head of strategy and operations' 'Head of Affiliates'
 'Agile Coach' 'Graphic & Web designer' 'Head of Corporate Strategy'
 'Embedded Engineer' 'Product designer' 'Research Assistant'
 'Chief Managed Security Solutions Officer' 'NLP Engineer'
 'Cybersecurity consultant' 'D365 CRM Developer' 'Product Content Manager'
 'Solution ArchitectSoftware Engineer / Software Developer'
 'Head of compensation and benefits' 'Implementer' 'Gis'
 'Java Engineering Lead' 'Head of UX/UI' 'Head of SEO'
 'Electronics Engineer' 'Pre-Match Trader' 'anti-fraud' 'Quality Manager'
 'Network Security Engineer' 'Data Annotation Manager' 'VoIP Engineer'
 'Head of Risk Management' 'Designer Generalist' 'Onboarding manager'
 'Low-code engineer' 'Head of IT department' 'Application Administrator'
 'Quantitative researcher' 'Scriptwriter']

### Categories

In [3098]:
print("categories",df2023['categories'].unique())
print("\n")
print("categories",df2024['categories'].unique())
print("\n")

categories ['QA' 'SE' 'DevOps' 'UI/UX, Product Design' 'Sales' 'Tech Leadership'
 'Other mgmt' 'Product Mgmt' 'HR' 'Support' 'Project Mgmt' 'Analyst'
 'Brand' 'DS' nan 'Marketing' 'Office manager / Admin / Assistant'
 'Agile Mgmt' 'Security' 'SysAdmin' 'Other Mgmt' 'General Leadership'
 'Artist/Animator' 'Finance /Accounting /Internal Audit' 'Design'
 'Tech Wr./Lclz' 'Legal' 'Consultant' 'Hardware' 'Game design' 'DBA'
 'Finance']


categories ['QA' 'SE' 'DevOps' 'UI/UX, Product Design' 'Sales' 'Tech Leadership'
 'Other mgmt' 'Product Mgmt' 'HR' 'Support' 'Project Mgmt' 'Analyst'
 'Brand' 'DS' nan 'Marketing' 'Office manager / Admin / Assistant'
 'Agile Mgmt' 'Security' 'SysAdmin' 'Other Mgmt' 'General Leadership'
 'Artist/Animator' 'Finance /Accounting /Internal Audit' 'Design'
 'Tech Wr./Lclz' 'Legal' 'Consultant' 'Hardware' 'Game design' 'DBA'
 'Finance']

### Age

In [3099]:
print("age",df2020['age'].unique())
print("\n")
print("age",df2021['age'].unique())
print("\n")
print("age",df2022['age'].unique())
print("\n")

age [31 36 33 42 25 32 30 24 38 35 28 23 41 37 29 34 40 26 39 44 45 27 46 21
 22 20 47 19 48 43 50 49 55 52 51 56 58 18 57 17 59 54 66 69]


age [32 20 26 19 29 22 28 33 35 36 25 30 23 21 27 31 34 40 38 39 24 37 44 42
 41 18 49 45 43 46 47 48 52 50 58 17 15 55 54 57 51 59 53 61 56 60 77 16]


age ['29' '36' '34' '23' '33' '31' '30' '24' '27' '17' '25' '20' '26' '22'
 '19' '21' '18' '32' '35' '28' '37' '43' '44' '39' '50' '40' '38' '41'
 '45' '42' '49' '46' '47' '48' '55' '63' '58' '53' '54' '51' '56' '60'
 '16' '57' '29,5' '52' '14']

In [3100]:
df2022['age'] = (
    df2022['age']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .astype(float)
    .round()
    .astype(int)
)

### English level

In [3101]:
print("english_level",df2020['english_level'].unique())
print("\n")
print("english_level",df2021['english_level'].unique())
print("\n")
print("english_level",df2022['english_level'].unique())
print("\n")
print("english_level",df2023['english_level'].unique())
print("\n")
print("english_level",df2024['english_level'].unique())
print("\n")

english_level [5 6 4 3 2]


english_level [3 5 4 6 2]


english_level [4 6 2 3 5]


english_level [5 6 3 4 2 1]


english_level [5 6 3 4 2 1]

### Salary

In [3102]:
print("salary",df2020['salary'].unique())
print("\n")
print("salary",df2021['salary'].unique())
print("\n")
print("salary",df2022['salary'].unique())
print("\n")
print([float(f) for f in df2023['salary'].unique() if pd.notna(f)])
print("\n")
print([float(f) for f in df2024['salary'].unique() if pd.notna(f)])
print("\n")

salary [ 3800 11600 11400 10000  9500  8500  4000  9000  1850  2500  3300  8000
  1500  6700  1000  9600  6800  3500  8770  8700  1750  5500  6000  6650
  8200   600  7500   560  2400  7800   800  7200  7695  6500  7410  7370
  7300  5000  7100  7000  1615  5400  1600   500  5300  7350  3000  6950
  6900  6825   550  6780  6100  2300  1400  4500  6600  5600  1350  1800
  2600   450  6300  6200   750  1300  5200  1250  4950   430  2100  6460
  1235  6400   400  6175  6150  5100  1200  6080   815  4800   370   356
   350  3285  4750   850  3200  3750  4700  4600   846   900  3700  2000
  1150  1100  5985  5950  5900  5800  3600  1140  4150  5750  5716  5700
   319   300  5670  5650  5605  1050  4655  4300   700  4275  2200  5720
  5375  4250  1900   980  5290  5275   950  5250  4200  2650  5225  4400
   935   930  3550   920  4100  5160  1700  5150  5130  5114  5050  5320
  5035  5023   669   285   865   740   860  3100  3325   830   295  1740
  2420   825   820  2375   290   460  2250   200   670   650  3900  3850
  2800  4996  4940  4900  1550  4860  4850  4830   423  3770   780   779
   770   280   250   760  2700  1330  4725  4705   735   730   725   723
   720   713   385  3650   705  4650  4645  4636  4630  4620  4910  4875
  4560  7600  4550  4523  4510   190   594  4180  3400  3040   680   675
   660   177  3150   380   642   640   630  2058   626  3250  4475  4465
  4460  4450   620  2731  3003  4350  4370  4360  4340  4335  3350  3050
  2080  2050  4240  4238  4235  2040  2900  4426   150  4190  4123  4110
   590   580  3190  3135  4085  4080   575  4050  2850  4046   570  4040
  1950   840   540   530   528   526   520   510  3020  2785   504  1776
   266  1525  2560  1775  2620  1450  1770  3990  3950  3928  1650  3880
  3878  3840  3833  3807   490   480   475   470  2550  8800  1680  1662
   440  3765  3762  3760   435   428  3720   425   420  3675  3666   414
  3640  3610   402  2477  2430  2750  3705  2741  3570   925  3515  2720
  2350  1580  2335  2320  2450   478  1570  2265  2150  5640   373   360
  3475  3470  3450  3430  3420  2185   812  3390   100  3380  3375  2003
   715  3275  3266   340  3230   336  1220  1282   335  3172  1425   333
  1995   317  3145  3120  1955  1945  1930  3290  3060  3031  3025  1385
  1860  1836  1560  1765  1755  1720  1715  1710  1920  7700  1670  1640
  1620  2950  2960  2945  2828  2925  2910  2813   456  1530  1520  1810
  2799  2780  2775  2770  2760  2755  2725  2630   927  2680  2670  2660
  1480  2640  1470  1460  2619  2615  2612  2610  1430  1415  2585  2565
   160   237  2520  2515  1190  3680  1760   390  1375  1367   230   893
  2470  1211  2480  1270  1260  2340  1240  2330  2325  1225  1095  1093
  1078  1060  2280  2260  2258  2256  2240  2230  2217   864  2160  2147
  1490  2145  2137  2135  1197  1180  1178  2090  2089  2070  2053  2051
  1120  3926  7050  1121  1356  3665  1054   714  3620   890   737  1310
  1980  1965  1045   710  1035   712  1888  1870  1865   970  1832  1830
  1820  1805   702  1230   338   915   910  1785  1780  4042  4035   320
   882  1689  1660  1630  1290  1610  3240   625   810   940  1590  1575
   962   914   912   907   617  1083  1070   960  3935   875   857  1486
  1485  1475   816  1440   785  1428  1420   753  1188  1370  1380   881
  1325  1320  1315   556   555   990  1280   955   775   709  1239  1196
  1170  1160   879   653  1110  1106  1102   784   465   892  1090  1072
   891   855  1080  1074   564  2530   429  1852   120   917   902   589
   885   880   877   870   677  2485   833   827  2385   443  2370  2821
   790   765  2815   652   130   633   695   685   673   666   665   824
   624   603   445   535   393   388   562   559   330   533   318   576
   525  9300  1960   485 15000   410 19000 30000   444  1515   375   427
   392   391   357 31600   321   352   293  1725  1390   315   260   270
   265  1366   220   210  1185   180   175   110]


salary ['950' '800' '788' '1200' '4500' '3000' '600' '1150' '3135' '1000' '1700'
 '900' '1900' '1400' '1100' '1080' '750' '1300' '1800' '5200' '710' '6500'
 '3500' '4800' '500' '1585' '10000' '3800' '2700' '4000' '1600' '1850'
 '1500' '2000' '550' '615' '970' '2950' '3678' '6000' '1054' '1050' '4510'
 '4900' '2800' '2500' '350' '770' '7500' '8000' '5000' '740' '4600' '4845'
 '4400' '3300' '700' '3600' '2400' '850' '400' '616' '450' '5100' '920'
 '3450' '4200' '4100' '8250' '2280' '6600' '1415' '175' '9600' '3250'
 '5250' '540' '2600' '520' '5300' '2900' '1450' '3100' '485' '730' '650'
 '2200' '780' '2100' '658' '370' '480' '1650' '6227' '940' '2300' '3290'
 '12000' '7000' '3750' '3040' '916' '425' '1520' '7200' '2850' '6400'
 '5500' '3325' '2750' '3200' '3900' '4300' '1950' '985' '1530' '6200'
 '1550' '11000' '4700' '3150' '1805' '4465' '7700' '6965' '4750' '2510'
 '1480' '1570' '820' '1140' '3700' '6900' '5700' '1470' '2450' '1250'
 '300' '1860' '1350' '1375' '7100' '1725' '3950' '889' '990' '8300' '720'
 '2350' '3350' '1385' '4250' '9000' '7600' '475' '1070' '2470' '2130'
 '3680' '2150' '586' '1380' '1075' '3335' '3370' '2650' '560' '6030'
 '9500' '3400' '3940' '2050' '718' '4275' '3650' '4150' '3790' '630'
 '5225' '1555' '4940' '4950' '1130' '2250' '5600' '6350' '479' '565'
 '6100' '1120' '1425' '6125' '1750' '3920' '570' '713' '1365' '4460'
 '1620' '2230' '6300' '2132' '4225' '620' '330' '4050' '5800' '1820'
 '2707' '665' '4350' '430' '4850' '1565' '3850' '3460' '2810' '5650' '618'
 '8500' '1320' '3190' '3749,7' '670' '220' '3560' '3050' '1045' '200'
 '2565' '640' '2090' '2175' '1430' '6650' '380' '5900' '880' '1440' '1290'
 '1190' '4179' '3060' '510' '810' '879' '660' '2931' '1680' '847' '13300'
 '490' '15000' '1280' '4370' '1655' '1622' '981' '930' '2040' '2375'
 '2330' '2160' '3180' '320' '3270' '333' '5750' '6340' '4650' '100' '3550'
 '2801,7' '910' '1660' '1254' '3230' '250' '2420' '2440' '2320' '2475'
 '1740' '3561' '7400' '365' '2415' '1990' '460' '2340' '5050' '2180' '366'
 '915' '898' '378' '1180' '745' '3275' '5175' '1020' '290' '1777' '890'
 '813' '2325' '6150' '530' '886' '4130' '4890' '664' '1230' '1240' '1923'
 '545' '185' '2660' '2999' '2120' '421' '555' '420' '1089' '870' '14000'
 '564' '445' '4136' '470' '680' '2632' '1094' '895' '2744' '1260' '617'
 '610' '1575' '5472' '1185' '825' '1460' '1569' '516,5' '5950' '1107'
 '1840' '738' '1870' '2135' '326' '995' '2326' '725' '10066' '8600' '3080'
 '1068' '1485' '180' '8200' '4229' '3625' '2125' '960' '436' '775' '1636'
 '999' '480,5' '441' '5170' '980' '2550' '2185' '760' '790' '735' '2085'
 '3420' '690' '2490' '3333' '1330' '1815' '575' '844' '737' '1777,7'
 '1420' '7900' '1360' '522' '385' '2754' '1675' '3515' '728' '840' '4560'
 '18000' '16000' '625' '492' '1370' '1124' '6270' '3260' '703' '705'
 '2680' '1775' '663,6' '1466' '925' '3610' '1490' '592' '7125' '1615'
 '4655' '1690' '3922' '4230' '8075' '17500' '9800' '3501' '13500' '1561'
 '587' '4120' '5400' '6800' '1995' '3239' '1904' '2890' '1730' '395' '426'
 '3760' '1090' '1720' '1685' '1160' '240' '945' '1874' '2260' '590' '2060'
 '525' '1334' '2517,5' '629' '2820' '1780' '1095' '734' '1980' '6700'
 '1174' '855' '4658' '2616' '5420' '150' '10350' '5350' '2111' '516'
 '3229' '1710' '10500' '16800' '15250' '14300' '13000' '11700' '11500'
 '11400' '11200' '10925' '10800' '10600' '10400' '10300' '9700' '9450'
 '9400' '9200' '9100' '8700' '8670' '8550' '8422' '8400' '8375' '8360'
 '8312' '8050' '7850' '7800' '7780' '7650' '7550' '7450' '7385' '7300'
 '7150' '7140' '7073' '7050' '6960' '6850' '6795' '6780' '6771' '6750'
 '6729' '6666' '6590' '6490' '6460' '6450' '6413' '6365' '6333' '6315'
 '6250' '6220' '6175' '6160' '6123' '6120' '5980' '5970' '5937' '5933'
 '5890' '5850' '5830' '5775' '5605' '5570' '5550' '5525' '5510' '5450'
 '5425' '5362' '5360' '5275' '5270' '5220' '5190' '5180' '5160' '5150'
 '5130' '5082' '5035' '5030' '5017' '5005' '4990' '4985' '4980' '4975'
 '4912' '4864' '4830' '4825' '4820' '4801' '4785' '4717' '4605' '4587'
 '4585' '4575' '4550' '4520' '4470' '4450' '4441' '4420' '4384' '4360'
 '4330' '4309' '4305' '4207' '4180' '4125' '4111' '4109' '4085' '4080'
 '4039' '4035' '4025' '4009' '3990' '3980' '3933' '3930' '3895' '3870'
 '3860' '3822' '3814' '3755' '3744' '3705' '3686' '3685' '3662' '3660'
 '3655' '3651' '3574' '3534' '3520' '3490' '3380' '3377' '3362' '3344'
 '3280' '3266' '3240' '3225' '3220' '3145' '3140' '3130' '3090' '3085'
 '2990' '2980' '2945' '2880' '2855' '2830' '2821' '2755' '2637' '2630'
 '2625' '2620' '2613' '2610' '2570' '2560' '2530' '2515' '2480' '2370'
 '2360' '2333' '2315' '2240' '2214' '2098' '2080' '2070' '2015' '1975'
 '1945' '1940' '1880' '1865' '1830' '1770' '1765' '1760' '1672' '1629'
 '1610' '1562' '1540' '1535' '1515' '1512' '1428' '1418' '1372' '1325'
 '1319' '1275' '1235' '1184' '1175' '1148' '1132' '1088' '1060' '1043'
 '1040' '828' '815' '773' '711' '675' '666' '645' '644' '612' '580' '577'
 '569' '548' '512' '499' '440' '415' '390' '375' '345' '340' '335' '325'
 '280']


salary ['4000' nan '2500' '500' '2800' '5500' '1400' '1200' '650' '6000' '6600'
 '850' '1000' '1500' '3000' '800' '700' '1100' '7500' '10600' '3300'
 '5000' '2400' '1800' '2100' '4500' '2600' '3600' '3525' '1600' '3200'
 '570' '6500' '4200' '1700' '5320' '5300' '1490' '1250' '2700' '4700'
 '1300' '400' '2000' '1577' '10000' '550' '5600' '950' '3550' '4750'
 '2200' '1850' '5200' '3040' '5100' '2250' '6450' '3500' '1900' '4400'
 '2865' '5350' '3700' '2850' '6150' '680' '2169' '1350' '2222' '2185'
 '2750' '3760' '2300' '200' '4275' '7700' '978' '1710' '1170' '3100'
 '5700' '1863' '2900' '3135' '3400' '4300' '730' '8500' '2240' '7000'
 '3650' '5400' '4800' '3800' '6700' '2920' '4100' '5800' '750' '2811'
 '330' '970' '900' '4250' '16000' '1050' '8300' '600' '2550' '3183' '7600'
 '2350' '6100' '3750' '6840' '6200' '780' '5185' '6800' '3230' '2330'
 '8000' '930' '3990' '1150' '5415' '100' '6300' '1750' '4340' '1080'
 '7125' '620' '6250' '2870' '6900' '4560' '2985' '5450' '4600' '3250'
 '833' '2950' '951' '2070' '4150' '3900' '376' '3285' '325' '2150' '300'
 '1425' '1010' '2050' '7400' '285' '3420' '5550' '1527' '475' '9000'
 '2230' '4845' '2570' '3050' '1390' '7800' '3850' '920' '8200' '3895'
 '955' '6650' '7200' '5225' '1032' '4850' '7570' '3621' '1180' '2525'
 '342' '810' '4720' '660' '3950' '1136' '345' '11000' '1475' '670' '5250'
 '2430' '560' '530' '980' '4930' '4650' '1470' '7300' '2145' '5510' '350'
 '4550' '3333' '450' '1270' '5650' '1933' '1990' '820' '3465' '5900'
 '5130' '9300' '7100' '960' '3920' '760' '11250' '7050' '1550' '2325'
 '4350' '2650' '1615' '4450' '5142' '2180' '3469' '6175' '4180' '425'
 '610' '4888' '1430' '580' '6666' '250' '7980' '1140' '6030' '1650' '1883'
 '3618' '14000' '1340' '9800' '2080' '2980' '4050' '375' '2520' '2450'
 '5050' '6270' '3450' '4900' '4810' '3380' '5870' '2831' '2280' '2620'
 '5375' '470' '3205' '6400' '3325' '6125' '615' '260' '671' '6825' '1370'
 '1277' '2340' '2245' '1410' '5750' '7840' '7150' '2840' '625' '5055'
 '5204' '1116' '1335' '1040' '3370' '3350' '4465' '1115' '2630' '1185'
 '4410' '720' '9500' '5150' '7900' '4020' '5180' '7220' '1310' '6135'
 '3160' '4980' '420' '2260' '2375' '1950' '815' '926' '3287' '9200' '190'
 '145' '6040' '4760' '5970' '1230' '5035' '597' '3330' '3344' '1575' '623'
 '6566' '2090' '8100' '480' '3530' '1682' '490' '8700' '3060' '4370'
 '4141' '1860' '3255' '1125' '940' '1670' '1764' '2177' '3150' '5160'
 '4112' '13900' '7030' '1220' '860' '12500' '10300' '3286' '1375' '2860'
 '2470' '2510' '795' '2241' '1995' '19500' '1090' '880' '6850' '5880'
 '2560' '1610' '909' '1154' '7550' '6460' '17000' '7187' '1006' '1542,75'
 '11675' '590' '1915' '3808' '240' '6050' '7050,82' '975' '8400' '3560'
 '2410' '7350' '4322' '2413' '3140' '1420' '1160' '160' '2908' '1830'
 '3870' '4080' '1146' '14500' '1580' '6386' '785' '7045' '1620' '4999'
 '2761' '2940' '290' '1825' '8800' '1565' '1377' '10750' '130' '1135'
 '2890' '3841' '4236' '6370' '547' '540' '8900' '640' '410' '4320' '870'
 '4895' '510' '1520' '910' '548' '380' '5040' '1865' '715' '3770' '3314'
 '2324' '2760' '1669' '3085' '3172' '430' '2063' '1590' '4430' '911'
 '2810' '10275' '1480' '1585' '2744' '2315' '4715' '8075' '866' '4801'
 '3571' '2945' '1639' '12000' '1224' '4940' '1690' '1260' '3570' '1640'
 '555' '3290' '1450' '1384' '1740' '1760' '1870' '957' '5522' '1591'
 '1045' '2965' '2660' '1330' '2380' '3185' '4655' '630' '3133' '6350'
 '637' '1440' '725' '1111' '4230' '7238' '1093' '2635' '758,4' '2425'
 '915' '5140' '270' '1540' '1280' '875' '435' '775' '6330' '872' '1696'
 '2337' '487' '1920' '9470' '5207' '6480' '3940' '575' '7893' '472' '825'
 '1770' '790' '144' '6750' '1235' '845' '5660' '5640' '3430' '3321' '5054'
 '520' '914' '1886' '7063' '405' '2023' '518' '655' '577' '2530' '675'
 '11700' '13200' '1785' '4950' '855' '2068' '6365' '3063' '2133' '5280'
 '1560' '10450' '11400' '340' '1680' '1205' '370' '4270' '5580' '12436'
 '3360' '2355' '1757' '997,54' '2420' '275' '495' '647' '4990' '1725'
 '5890' '1880' '7450' '2667' '8125' '1541' '1380' '770' '2875' '935'
 '3404,33' '10900' '3965' '8550' '4085' '812' '4725' '582' '6637' '2052'
 '11100' '215' '8001' '565,5' '320' '1192' '719' '740' '2577' '3885' '735'
 '1284,78' '504' '2412' '8600' '925' '2225' '6550' '1244,5' '3375' '1623'
 '756' '150' '180' '6996' '5850' '569' '210' '6130' '2040' '2033' '2715'
 '10500' '546' '1970' '1907' '1130' '2755' '2432' '1327' '1089' '3491'
 '2160' '230' '10200' '6325' '1120' '3515' '2025' '390' '1633' '9100'
 '4225' '690' '1729' '885' '80' '2156' '2370' '14687' '1525' '1110' '4425'
 '1052' '2990' '1720' '13000' '9450' '4870' '942' '2565' '6935' '6120'
 '3002,69' '280' '414' '2880' '6080' '2453' '890' '1385' '3610' '3845'
 '6140' '798' '5260' '4030' '7250' '8445' '6950' '1584' '1660' '4880'
 '7166' '3280' '5287' '5775' '665' '1225' '415' '4360' '225' '217' '1255'
 '5432' '5776' '3896' '4210' '1223' '1030' '1624' '3470' '847' '3180'
 '1530' '1562' '50' '2190' '4072' '1068' '1256' '1556' '319' '830' '1063'
 '824' '2125' '492' '2770' '617' '2277' '6526' '7083' '1268' '1060' '3095'
 '840' '3908' '1513' '1671' '5667' '7320' '4740' '3480' '4802' '1955'
 '2610' '4530' '2170' '1368' '3670' '4480' '1251' '882' '5411' '835' '460'
 '1912' '5036' '4137' '3720' '459' '3855' '440' '6860' '5373' '3120'
 '2034' '224' '433' '934' '542' '1730' '6792' '9400' '2612' '1711' '1805'
 '4926' '2128' '1465' '9310' '1765' '523' '1122' '6272' '1945' '468'
 '5440' '2404' '2244' '2055' '327' '745' '5275' '3683' '628' '3833' '2729'
 '2616' '677' '1810' '988' '2220' '2480' '12100' '1782' '5340' '310'
 '9600' '995' '1275' '5836' '5860' '2665' '784' '1195' '3520' '243,76'
 '1448' '4044,69' '908' '3830' '956' '220' '2335' '1472' '1075' '476'
 '8150' '2978' '1468' '685' '360' '4330' '2675' '3044' '2625' '1155'
 '1570' '7425' '1360' '4456' '683' '324' '3740' '5470' '4970' '1190'
 '1666' '1641' '9285' '2206' '3215' '826' '6790' '743' '4224' '4830'
 '1820' '710' '7175' '12600' '2285' '1274' '1596' '3145' '545' '1320'
 '589' '533' '2780' '5115' '1663' '563' '5162' '5190' '1408' '5950' '7375'
 '1528' '1325' '491' '2111' '5454' '1175' '1326' '272' '467' '2060' '1717'
 '2975' '1156' '3790' '958' '876' '407' '271' '3975' '163' '2165' '1930']



In [3103]:
df2021['salary'] = (
    df2021['salary']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .astype(float)
    .round()
    .astype("Int64")
)

df2022['salary'] = (
    df2022['salary']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .astype(float)
    .round()
    .astype("Int64")
)


df2023['salary'] = (
    df2023['salary']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .astype(float)
    .round()
    .astype("Int64")
)

df2024['salary'] = (
    df2024['salary']
    .astype(str)
    .str.replace(',', '.', regex=False)
    .astype(float)
    .round()
    .astype("Int64")
)

### PhD

In [3104]:
print("phd",df2020['phd'].unique())
print("\n")
print("phd",df2021['phd'].unique())
print("\n")
print("phd",df2022['phd'].unique())
print("\n")

phd ['Немає' 'Кандидат наук']


phd ['Немає' 'Кандидат наук' 'Доктор наук' 'Кандидат наук / PhD' nan]


phd ['Немає' 'Кандидат наук / PhD' 'Доктор наук' nan]

In [3105]:
df2021['phd'] = df2021['phd'].replace({'Кандидат наук / PhD': 'Кандидат наук'})
df2022['phd'] = df2022['phd'].replace({'Кандидат наук / PhD': 'Кандидат наук'})

## Forming CSV

In [3106]:
df2020.to_csv('Salaries Dec 2020 cleaned.csv', index=False)
df2020.columns

df2021.to_csv('Salaries Dec 2021 cleaned.csv', index=False)
df2021.columns

df2022.to_csv('Salaries Dec 2022 cleaned.csv', index=False)
df2022.columns

df2023.to_csv('Salaries Dec 2023 cleaned.csv', index=False)
df2023.columns

df2024.to_csv('Salaries Dec 2024 cleaned.csv', index=False)
df2024.columns

Index(['timestamp', 'full_time', 'salary', 'title', 'programming_language',
       'company_type', 'english_level', 'region', 'male', 'categories',
       'position'],
      dtype='object')

## Dataset.head()

In [3107]:
df2020.head()

,timestamp,full_time,region,work_site,male,age,education,university,english_level,position,...,programming_language,industry,company_type,number_of_employees,total_experience,tenure,salary,salary_change,bonus,phd
0,07/12/2020 13:06,1,Київ,Віддалено,1,31,Вища,НТУУ «КПІ»,5,Support,...,NaN,Telecom,Аутсорсингова,до 1000,8.0,7.0,3800,-1520.0,4000,Немає
1,12/12/2020 11:33,1,Київ,Віддалено,1,36,Вища,ХНУРЕ,5,"Software Engineer (Junior, Middle, Senior, Tea...",...,Java,"Fintech, Medtech",Аутсорсингова,понад 1000,10.0,2.0,11600,5000.0,1000,Немає
2,08/12/2020 20:21,1,Київ,Віддалено,1,31,Вища,НТУУ «КПІ»,6,"Software Engineer (Junior, Middle, Senior, Tea...",...,Kotlin,Інша,Продуктова,Лише я,8.0,1.0,11400,1000.0,1100,Немає
3,08/12/2020 12:45,1,Київ,"Частково віддалено, частково в офісі",1,33,Вища,КНУБА,4,"Software Engineer (Junior, Middle, Senior, Tea...",...,1С,"E-commerce, ERP, Інша",Продуктова,понад 1000,10.0,3.0,10000,1000.0,<NA>,Немає
4,07/12/2020 10:47,1,Дніпро,"Частково віддалено, частково в офісі",1,42,Вища,NaN,5,"Project/Product/Program Manager, Product Owner...",...,NaN,Інша,Продуктова,до 50,10.0,10.0,9500,100.0,30000,Немає

In [3108]:
df2021.head()

,timestamp,full_time,region,work_site,male,age,education,phd,english_level,position,title,programming_language,industry,company_type,number_of_employees,total_experience,salary,salary_change,bonus
0,29/11/2021 09:28,0,Харків,"Частково віддалено, частково в офісі",1,32,Вища,Немає,3,"Marketing, SEO, Copywriter",Middle,NaN,"E-commerce, Fintech, Manufacturing",Аутсорсингова,до 50,6.0,950,350.0,300
1,29/11/2021 09:29,1,Київ,"Частково віддалено, частково в офісі",0,20,Студент,Немає,5,HR,Junior,NaN,"E-commerce, Edtech",Аутсорсингова,до 200,1.0,800,200.0,<NA>
2,29/11/2021 09:30,1,Черкаси,В офісі,1,26,Вища,Немає,5,"Project/Product/Program Manager, Product Owner...",Junior,NaN,"E-commerce, Legal",Продуктова,до 200,0.5,788,0.0,<NA>
3,29/11/2021 09:31,1,Київ,"Частково віддалено, частково в офісі",1,19,Середня,Немає,5,"Project/Product/Program Manager, Product Owner...",Junior,NaN,Health & Fitness,Продуктова,до 1000,0.5,1200,600.0,<NA>
4,29/11/2021 09:32,1,Суми,Віддалено,1,29,Вища,Немає,4,"DevOps, SysAdmin",Senior,Python,E-commerce,Продуктова,до 200,3.0,4500,1500.0,<NA>

In [3109]:
df2022.head()

,timestamp,full_time,region,salary,male,age,education,phd,english_level,position,title,programming_language,industry,company_type,total_experience
0,30/11/2022 10:26,0,Івано-Франківськ,4000,1,29,Вища,Немає,4,"Designer / Artist (Graphic, UX/UI, Game, Artis...",Team Lead,NaN,Blockchain,Стартап,8.0
1,30/11/2022 10:26,1,Не Україна,<NA>,1,36,Вища,Немає,6,"Software Engineer (Junior, Middle, Senior, Tea...",Middle,Ruby,Public services / Government,Продуктова,3.0
2,30/11/2022 10:26,1,Київ,2500,1,34,Вища,Немає,2,"Software Engineer (Junior, Middle, Senior, Tea...",Middle,C# / .NET,"Adtech / Advertising, Security, Telecom",Продуктова,4.0
3,30/11/2022 10:27,1,Львів,500,0,23,Вища,Немає,3,"QA Engineer (Junior, Middle, Senior, Team/Tech...",Junior,NaN,Telecom,Продуктова,0.5
4,30/11/2022 10:27,0,Житомир,2800,0,33,Вища,Немає,5,"QA Engineer (Junior, Middle, Senior, Team/Tech...",Senior,NaN,Automotive,Продуктова,6.0

In [3110]:
df2023.head()

,timestamp,full_time,salary,title,programming_language,company_type,total_experience,english_level,region,male,categories,position
0,22/11/2024 11:03,1,800,Middle,TypeScript,Аутсорсингова,2.0,5,Львів,1,QA,Manual QA
1,22/11/2024 11:04,1,5000,Head,TypeScript,Продуктова,10.0,5,Київ,1,QA,Head of QA
2,22/11/2024 11:21,1,4300,NaN,C# / .NET,Продуктова,10.0,5,Хмельницький,1,QA,Automation QA / AQA
3,22/11/2024 13:20,1,6000,Head,Python,Аутсорсингова,15.0,6,Не Україна,1,QA,Head of QA
4,22/11/2024 13:47,1,2700,Middle,TypeScript,Продуктова,4.0,5,Київ,1,SE,Software Engineer / Software Developer

In [3111]:
df2024.head()

,timestamp,full_time,salary,title,programming_language,company_type,english_level,region,male,categories,position
0,22/11/2024 11:03,1,800,Middle,TypeScript,Аутсорсингова,5,Львів,0,QA,Manual QA
1,22/11/2024 11:04,1,5000,Head,TypeScript,Продуктова,5,Київ,1,QA,Head of QA
2,22/11/2024 11:21,1,4300,NaN,C# / .NET,Продуктова,5,Хмельницький,1,QA,Automation QA / AQA
3,22/11/2024 13:20,1,6000,Head,Python,Аутсорсингова,6,Не Україна,1,QA,Head of QA
4,22/11/2024 13:47,1,2700,Middle,TypeScript,Продуктова,5,Київ,1,SE,Software Engineer / Software Developer